<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ciudad;
use App\Models\Departamento;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            // Amazonas (91)
            ['cod_dep' => '91', 'codigo' => '91001', 'nombre' => 'LETICIA'],
            ['cod_dep' => '91', 'codigo' => '91263', 'nombre' => 'EL ENCANTO'],
            ['cod_dep' => '91', 'codigo' => '91405', 'nombre' => 'LA CHORRERA'],
            ['cod_dep' => '91', 'codigo' => '91407', 'nombre' => 'LA PEDRERA'],
            ['cod_dep' => '91', 'codigo' => '91430', 'nombre' => 'LA VICTORIA'],
            ['cod_dep' => '91', 'codigo' => '91460', 'nombre' => 'MIRITÍ – PARANÁ'],
            ['cod_dep' => '91', 'codigo' => '91530', 'nombre' => 'PUERTO ALEGRÍA'],
            ['cod_dep' => '91', 'codigo' => '91536', 'nombre' => 'PUERTO ARICA'],
            ['cod_dep' => '91', 'codigo' => '91540', 'nombre' => 'PUERTO NARIÑO'],
            ['cod_dep' => '91', 'codigo' => '91669', 'nombre' => 'PUERTO SANTANDER'],
            ['cod_dep' => '91', 'codigo' => '91798', 'nombre' => 'TARAPACÁ'],
            
            // Antioquia (05)
            ['cod_dep' => '05', 'codigo' => '05001', 'nombre' => 'MEDELLÍN'],
            ['cod_dep' => '05', 'codigo' => '05002', 'nombre' => 'ABEJORRAL'],
            ['cod_dep' => '05', 'codigo' => '05004', 'nombre' => 'ABRIAQUÍ'],
            ['cod_dep' => '05', 'codigo' => '05021', 'nombre' => 'ALEJANDRÍA'],
            ['cod_dep' => '05', 'codigo' => '05030', 'nombre' => 'AMAGÁ'],
            ['cod_dep' => '05', 'codigo' => '05031', 'nombre' => 'AMALFI'],
            ['cod_dep' => '05', 'codigo' => '05034', 'nombre' => 'ANDES'],
            ['cod_dep' => '05', 'codigo' => '05036', 'nombre' => 'ANGELÓPOLIS'],
            ['cod_dep' => '05', 'codigo' => '05038', 'nombre' => 'ANGOSTURA'],
            ['cod_dep' => '05', 'codigo' => '05040', 'nombre' => 'ANORÍ'],
            ['cod_dep' => '05', 'codigo' => '05042', 'nombre' => 'SANTA FÉ DE ANTIOQUIA'],
            ['cod_dep' => '05', 'codigo' => '05044', 'nombre' => 'ANZÁ'],
            ['cod_dep' => '05', 'codigo' => '05045', 'nombre' => 'APARTADÓ'],
            ['cod_dep' => '05', 'codigo' => '05051', 'nombre' => 'ARBOLETES'],
            ['cod_dep' => '05', 'codigo' => '05055', 'nombre' => 'ARGELIA'],
            ['cod_dep' => '05', 'codigo' => '05059', 'nombre' => 'ARMENIA'],
            ['cod_dep' => '05', 'codigo' => '05079', 'nombre' => 'BARBOSA'],
            ['cod_dep' => '05', 'codigo' => '05086', 'nombre' => 'BELMIRA'],
            ['cod_dep' => '05', 'codigo' => '05088', 'nombre' => 'BELLO'],
            ['cod_dep' => '05', 'codigo' => '05091', 'nombre' => 'BETANIA'],
            ['cod_dep' => '05', 'codigo' => '05093', 'nombre' => 'BETULIA'],
            ['cod_dep' => '05', 'codigo' => '05101', 'nombre' => 'CIUDAD BOLÍVAR'],
            ['cod_dep' => '05', 'codigo' => '05107', 'nombre' => 'BRICEÑO'],
            ['cod_dep' => '05', 'codigo' => '05113', 'nombre' => 'BURITICÁ'],
            ['cod_dep' => '05', 'codigo' => '05120', 'nombre' => 'CÁCERES'],
            ['cod_dep' => '05', 'codigo' => '05125', 'nombre' => 'CAICEDO'],
            ['cod_dep' => '05', 'codigo' => '05129', 'nombre' => 'CALDAS'],
            ['cod_dep' => '05', 'codigo' => '05134', 'nombre' => 'CAMPAMENTO'],
            ['cod_dep' => '05', 'codigo' => '05138', 'nombre' => 'CAÑASGORDAS'],
            ['cod_dep' => '05', 'codigo' => '05142', 'nombre' => 'CARACOLÍ'],
            ['cod_dep' => '05', 'codigo' => '05145', 'nombre' => 'CARAMANTA'],
            ['cod_dep' => '05', 'codigo' => '05147', 'nombre' => 'CAREPA'],
            ['cod_dep' => '05', 'codigo' => '05148', 'nombre' => 'EL CARMEN DE VIBORAL'],
            ['cod_dep' => '05', 'codigo' => '05150', 'nombre' => 'CAROLINA'],
            ['cod_dep' => '05', 'codigo' => '05154', 'nombre' => 'CAUCASIA'],
            ['cod_dep' => '05', 'codigo' => '05172', 'nombre' => 'CHIGORODÓ'],
            ['cod_dep' => '05', 'codigo' => '05190', 'nombre' => 'CISNEROS'],
            ['cod_dep' => '05', 'codigo' => '05197', 'nombre' => 'COCORNÁ'],
            ['cod_dep' => '05', 'codigo' => '05206', 'nombre' => 'CONCEPCIÓN'],
            ['cod_dep' => '05', 'codigo' => '05209', 'nombre' => 'CONCORDIA'],
            ['cod_dep' => '05', 'codigo' => '05212', 'nombre' => 'COPACABANA'],
            ['cod_dep' => '05', 'codigo' => '05234', 'nombre' => 'DABEIBA'],
            ['cod_dep' => '05', 'codigo' => '05237', 'nombre' => 'DONMATÍAS'],
            ['cod_dep' => '05', 'codigo' => '05240', 'nombre' => 'EBÉJICO'],
            ['cod_dep' => '05', 'codigo' => '05250', 'nombre' => 'EL BAGRE'],
            ['cod_dep' => '05', 'codigo' => '05264', 'nombre' => 'ENTRERRÍOS'],
            ['cod_dep' => '05', 'codigo' => '05266', 'nombre' => 'ENVIGADO'],
            ['cod_dep' => '05', 'codigo' => '05282', 'nombre' => 'FREDONIA'],
            ['cod_dep' => '05', 'codigo' => '05284', 'nombre' => 'FRONTINO'],
            ['cod_dep' => '05', 'codigo' => '05306', 'nombre' => 'GIRALDO'],
            ['cod_dep' => '05', 'codigo' => '05308', 'nombre' => 'GIRARDOTA'],
            ['cod_dep' => '05', 'codigo' => '05310', 'nombre' => 'GÓMEZ PLATA'],
            ['cod_dep' => '05', 'codigo' => '05313', 'nombre' => 'GRANADA'],
            ['cod_dep' => '05', 'codigo' => '05315', 'nombre' => 'GUADALUPE'],
            ['cod_dep' => '05', 'codigo' => '05318', 'nombre' => 'GUARNE'],
            ['cod_dep' => '05', 'codigo' => '05321', 'nombre' => 'GUATAPÉ'],
            ['cod_dep' => '05', 'codigo' => '05347', 'nombre' => 'HELICONIA'],
            ['cod_dep' => '05', 'codigo' => '05353', 'nombre' => 'HISPANIA'],
            ['cod_dep' => '05', 'codigo' => '05360', 'nombre' => 'ITAGÜÍ'],
            ['cod_dep' => '05', 'codigo' => '05361', 'nombre' => 'ITUANGO'],
            ['cod_dep' => '05', 'codigo' => '05364', 'nombre' => 'JARDÍN'],
            ['cod_dep' => '05', 'codigo' => '05368', 'nombre' => 'JERICÓ'],
            ['cod_dep' => '05', 'codigo' => '05376', 'nombre' => 'LA CEJA'],
            ['cod_dep' => '05', 'codigo' => '05380', 'nombre' => 'LA ESTRELLA'],
            ['cod_dep' => '05', 'codigo' => '05390', 'nombre' => 'LA PINTADA'],
            ['cod_dep' => '05', 'codigo' => '05400', 'nombre' => 'LA UNIÓN'],
            ['cod_dep' => '05', 'codigo' => '05411', 'nombre' => 'LIBORINA'],
            ['cod_dep' => '05', 'codigo' => '05425', 'nombre' => 'MACEO'],
            ['cod_dep' => '05', 'codigo' => '05440', 'nombre' => 'MARINILLA'],
            ['cod_dep' => '05', 'codigo' => '05467', 'nombre' => 'MONTEBELLO'],
            ['cod_dep' => '05', 'codigo' => '05475', 'nombre' => 'MURINDÓ'],
            ['cod_dep' => '05', 'codigo' => '05480', 'nombre' => 'MUTATÁ'],
            ['cod_dep' => '05', 'codigo' => '05483', 'nombre' => 'NARIÑO'],
            ['cod_dep' => '05', 'codigo' => '05490', 'nombre' => 'NECOCLÍ'],
            ['cod_dep' => '05', 'codigo' => '05495', 'nombre' => 'NECHÍ'],
            ['cod_dep' => '05', 'codigo' => '05501', 'nombre' => 'OLAYA'],
            ['cod_dep' => '05', 'codigo' => '05541', 'nombre' => 'PEÑOL'],
            ['cod_dep' => '05', 'codigo' => '05543', 'nombre' => 'PEQUE'],
            ['cod_dep' => '05', 'codigo' => '05576', 'nombre' => 'PUEBLORRICO'],
            ['cod_dep' => '05', 'codigo' => '05579', 'nombre' => 'PUERTO BERRÍO'],
            ['cod_dep' => '05', 'codigo' => '05585', 'nombre' => 'PUERTO NARE'],
            ['cod_dep' => '05', 'codigo' => '05591', 'nombre' => 'PUERTO TRIUNFO'],
            ['cod_dep' => '05', 'codigo' => '05604', 'nombre' => 'REMEDIOS'],
            ['cod_dep' => '05', 'codigo' => '05607', 'nombre' => 'RETIRO'],
            ['cod_dep' => '05', 'codigo' => '05615', 'nombre' => 'RIONEGRO'],
            ['cod_dep' => '05', 'codigo' => '05628', 'nombre' => 'SABANALARGA'],
            ['cod_dep' => '05', 'codigo' => '05631', 'nombre' => 'SABANETA'],
            ['cod_dep' => '05', 'codigo' => '05642', 'nombre' => 'SALGAR'],
            ['cod_dep' => '05', 'codigo' => '05647', 'nombre' => 'SAN ANDRÉS DE CUERQUÍA'],
            ['cod_dep' => '05', 'codigo' => '05649', 'nombre' => 'SAN CARLOS'],
            ['cod_dep' => '05', 'codigo' => '05652', 'nombre' => 'SAN FRANCISCO'],
            ['cod_dep' => '05', 'codigo' => '05656', 'nombre' => 'SAN JERÓNIMO'],
            ['cod_dep' => '05', 'codigo' => '05658', 'nombre' => 'SAN JOSÉ DE LA MONTAÑA'],
            ['cod_dep' => '05', 'codigo' => '05659', 'nombre' => 'SAN JUAN DE URABÁ'],
            ['cod_dep' => '05', 'codigo' => '05660', 'nombre' => 'SAN LUIS'],
            ['cod_dep' => '05', 'codigo' => '05664', 'nombre' => 'SAN PEDRO DE LOS MILAGROS'],
            ['cod_dep' => '05', 'codigo' => '05665', 'nombre' => 'SAN PEDRO DE URABÁ'],
            ['cod_dep' => '05', 'codigo' => '05667', 'nombre' => 'SAN RAFAEL'],
            ['cod_dep' => '05', 'codigo' => '05670', 'nombre' => 'SAN ROQUE'],
            ['cod_dep' => '05', 'codigo' => '05674', 'nombre' => 'SAN VICENTE FERRER'],
            ['cod_dep' => '05', 'codigo' => '05679', 'nombre' => 'SANTA BÁRBARA'],
            ['cod_dep' => '05', 'codigo' => '05686', 'nombre' => 'SANTA ROSA DE OSOS'],
            ['cod_dep' => '05', 'codigo' => '05690', 'nombre' => 'SANTO DOMINGO'],
            ['cod_dep' => '05', 'codigo' => '05697', 'nombre' => 'EL SANTUARIO'],
            ['cod_dep' => '05', 'codigo' => '05736', 'nombre' => 'SEGOVIA'],
            ['cod_dep' => '05', 'codigo' => '05756', 'nombre' => 'SONSÓN'],
            ['cod_dep' => '05', 'codigo' => '05761', 'nombre' => 'SOPETRÁN'],
            ['cod_dep' => '05', 'codigo' => '05789', 'nombre' => 'TÁMESIS'],
            ['cod_dep' => '05', 'codigo' => '05790', 'nombre' => 'TARAZÁ'],
            ['cod_dep' => '05', 'codigo' => '05792', 'nombre' => 'TARSO'],
            ['cod_dep' => '05', 'codigo' => '05809', 'nombre' => 'TITIRIBÍ'],
            ['cod_dep' => '05', 'codigo' => '05819', 'nombre' => 'TOLEDO'],
            ['cod_dep' => '05', 'codigo' => '05837', 'nombre' => 'TURBO'],
            ['cod_dep' => '05', 'codigo' => '05842', 'nombre' => 'URAMITA'],
            ['cod_dep' => '05', 'codigo' => '05847', 'nombre' => 'URRAO'],
            ['cod_dep' => '05', 'codigo' => '05854', 'nombre' => 'VALDIVIA'],
            ['cod_dep' => '05', 'codigo' => '05856', 'nombre' => 'VALPARAÍSO'],
            ['cod_dep' => '05', 'codigo' => '05858', 'nombre' => 'VEGACHÍ'],
            ['cod_dep' => '05', 'codigo' => '05861', 'nombre' => 'VENECIA'],
            ['cod_dep' => '05', 'codigo' => '05873', 'nombre' => 'VIGÍA DEL FUERTE'],
            ['cod_dep' => '05', 'codigo' => '05885', 'nombre' => 'YALÍ'],
            ['cod_dep' => '05', 'codigo' => '05887', 'nombre' => 'YARUMAL'],
            ['cod_dep' => '05', 'codigo' => '05890', 'nombre' => 'YOLOMBÓ'],
            ['cod_dep' => '05', 'codigo' => '05893', 'nombre' => 'YONDÓ'],
            ['cod_dep' => '05', 'codigo' => '05895', 'nombre' => 'ZARAGOZA'],
            
            // Arauca (81)
            ['cod_dep' => '81', 'codigo' => '81001', 'nombre' => 'ARAUCA'],
            ['cod_dep' => '81', 'codigo' => '81065', 'nombre' => 'ARAUQUITA'],
            ['cod_dep' => '81', 'codigo' => '81220', 'nombre' => 'CRAVO NORTE'],
            ['cod_dep' => '81', 'codigo' => '81300', 'nombre' => 'FORTUL'],
            ['cod_dep' => '81', 'codigo' => '81591', 'nombre' => 'PUERTO RONDÓN'],
            ['cod_dep' => '81', 'codigo' => '81736', 'nombre' => 'SARAVENA'],
            ['cod_dep' => '81', 'codigo' => '81794', 'nombre' => 'TAME'],
        ];

        // San Andrés (88), Atlántico (08), Bolívar (13), Boyacá (15)
        $batch2 = [
            // San Andrés, Providencia y Santa Catalina (88)
            ['cod_dep' => '88', 'codigo' => '88001', 'nombre' => 'SAN ANDRÉS'],
            ['cod_dep' => '88', 'codigo' => '88564', 'nombre' => 'PROVIDENCIA'],

            // Atlántico (08)
            ['cod_dep' => '08', 'codigo' => '08001', 'nombre' => 'BARRANQUILLA'],
            ['cod_dep' => '08', 'codigo' => '08078', 'nombre' => 'BARANOA'],
            ['cod_dep' => '08', 'codigo' => '08137', 'nombre' => 'CAMPO DE LA CRUZ'],
            ['cod_dep' => '08', 'codigo' => '08141', 'nombre' => 'CANDELARIA'],
            ['cod_dep' => '08', 'codigo' => '08296', 'nombre' => 'GALAPA'],
            ['cod_dep' => '08', 'codigo' => '08372', 'nombre' => 'JUAN DE ACOSTA'],
            ['cod_dep' => '08', 'codigo' => '08421', 'nombre' => 'LURUACO'],
            ['cod_dep' => '08', 'codigo' => '08433', 'nombre' => 'MALAMBO'],
            ['cod_dep' => '08', 'codigo' => '08436', 'nombre' => 'MANATÍ'],
            ['cod_dep' => '08', 'codigo' => '08520', 'nombre' => 'PALMAR DE VARELA'],
            ['cod_dep' => '08', 'codigo' => '08549', 'nombre' => 'PIOJÓ'],
            ['cod_dep' => '08', 'codigo' => '08558', 'nombre' => 'POLONUEVO'],
            ['cod_dep' => '08', 'codigo' => '08560', 'nombre' => 'PONEDERA'],
            ['cod_dep' => '08', 'codigo' => '08573', 'nombre' => 'PUERTO COLOMBIA'],
            ['cod_dep' => '08', 'codigo' => '08606', 'nombre' => 'REPELÓN'],
            ['cod_dep' => '08', 'codigo' => '08634', 'nombre' => 'SABANAGRANDE'],
            ['cod_dep' => '08', 'codigo' => '08638', 'nombre' => 'SABANALARGA'],
            ['cod_dep' => '08', 'codigo' => '08675', 'nombre' => 'SANTA LUCÍA'],
            ['cod_dep' => '08', 'codigo' => '08685', 'nombre' => 'SANTO TOMÁS'],
            ['cod_dep' => '08', 'codigo' => '08758', 'nombre' => 'SOLEDAD'],
            ['cod_dep' => '08', 'codigo' => '08770', 'nombre' => 'SUAN'],
            ['cod_dep' => '08', 'codigo' => '08832', 'nombre' => 'TUBARÁ'],
            ['cod_dep' => '08', 'codigo' => '08849', 'nombre' => 'USIACURÍ'],

            // Bogotá D.C. (11)
            ['cod_dep' => '11', 'codigo' => '11001', 'nombre' => 'BOGOTÁ, D.C.'],

            // Bolívar (13)
            ['cod_dep' => '13', 'codigo' => '13001', 'nombre' => 'CARTAGENA DE INDIAS'],
            ['cod_dep' => '13', 'codigo' => '13006', 'nombre' => 'ACHÍ'],
            ['cod_dep' => '13', 'codigo' => '13030', 'nombre' => 'ALTOS DEL ROSARIO'],
            ['cod_dep' => '13', 'codigo' => '13042', 'nombre' => 'ARENAL'],
            ['cod_dep' => '13', 'codigo' => '13052', 'nombre' => 'ARJONA'],
            ['cod_dep' => '13', 'codigo' => '13062', 'nombre' => 'ARROYOHONDO'],
            ['cod_dep' => '13', 'codigo' => '13074', 'nombre' => 'BARRANCO DE LOBA'],
            ['cod_dep' => '13', 'codigo' => '13140', 'nombre' => 'CALAMAR'],
            ['cod_dep' => '13', 'codigo' => '13160', 'nombre' => 'CANTAGALLO'],
            ['cod_dep' => '13', 'codigo' => '13188', 'nombre' => 'CICUCO'],
            ['cod_dep' => '13', 'codigo' => '13212', 'nombre' => 'CÓRDOBA'],
            ['cod_dep' => '13', 'codigo' => '13222', 'nombre' => 'CLEMENCIA'],
            ['cod_dep' => '13', 'codigo' => '13244', 'nombre' => 'EL CARMEN DE BOLÍVAR'],
            ['cod_dep' => '13', 'codigo' => '13248', 'nombre' => 'EL GUAMO'],
            ['cod_dep' => '13', 'codigo' => '13268', 'nombre' => 'EL PEÑÓN'],
            ['cod_dep' => '13', 'codigo' => '13300', 'nombre' => 'HATILLO DE LOBA'],
            ['cod_dep' => '13', 'codigo' => '13430', 'nombre' => 'MAGANGUÉ'],
            ['cod_dep' => '13', 'codigo' => '13433', 'nombre' => 'MAHATES'],
            ['cod_dep' => '13', 'codigo' => '13440', 'nombre' => 'MARGARITA'],
            ['cod_dep' => '13', 'codigo' => '13442', 'nombre' => 'MARÍA LA BAJA'],
            ['cod_dep' => '13', 'codigo' => '13458', 'nombre' => 'MONTECRISTO'],
            ['cod_dep' => '13', 'codigo' => '13468', 'nombre' => 'MOMPÓS'],
            ['cod_dep' => '13', 'codigo' => '13473', 'nombre' => 'MORALES'],
            ['cod_dep' => '13', 'codigo' => '13490', 'nombre' => 'NOROSÍ'],
            ['cod_dep' => '13', 'codigo' => '13549', 'nombre' => 'PINILLOS'],
            ['cod_dep' => '13', 'codigo' => '13580', 'nombre' => 'REGIDOR'],
            ['cod_dep' => '13', 'codigo' => '13600', 'nombre' => 'RÍO VIEJO'],
            ['cod_dep' => '13', 'codigo' => '13620', 'nombre' => 'SAN CRISTÓBAL'],
            ['cod_dep' => '13', 'codigo' => '13647', 'nombre' => 'SAN ESTANISLAO'],
            ['cod_dep' => '13', 'codigo' => '13650', 'nombre' => 'SAN FERNANDO'],
            ['cod_dep' => '13', 'codigo' => '13654', 'nombre' => 'SAN JACINTO'],
            ['cod_dep' => '13', 'codigo' => '13655', 'nombre' => 'SAN JACINTO DEL CAUCA'],
            ['cod_dep' => '13', 'codigo' => '13657', 'nombre' => 'SAN JUAN NEPOMUCENO'],
            ['cod_dep' => '13', 'codigo' => '13667', 'nombre' => 'SAN MARTÍN DE LOBA'],
            ['cod_dep' => '13', 'codigo' => '13670', 'nombre' => 'SAN PABLO SUR'],
            ['cod_dep' => '13', 'codigo' => '13673', 'nombre' => 'SANTA CATALINA'],
            ['cod_dep' => '13', 'codigo' => '13683', 'nombre' => 'SANTA ROSA DE LIMA'],
            ['cod_dep' => '13', 'codigo' => '13688', 'nombre' => 'SANTA ROSA DEL SUR'],
            ['cod_dep' => '13', 'codigo' => '13744', 'nombre' => 'SIMITÍ'],
            ['cod_dep' => '13', 'codigo' => '13760', 'nombre' => 'SOPLAVIENTO'],
            ['cod_dep' => '13', 'codigo' => '13780', 'nombre' => 'TALAIGUA NUEVO'],
            ['cod_dep' => '13', 'codigo' => '13810', 'nombre' => 'TIQUISIO'],
            ['cod_dep' => '13', 'codigo' => '13836', 'nombre' => 'TURBACO'],
            ['cod_dep' => '13', 'codigo' => '13838', 'nombre' => 'TURBANÁ'],
            ['cod_dep' => '13', 'codigo' => '13873', 'nombre' => 'VILLANUEVA'],
            ['cod_dep' => '13', 'codigo' => '13894', 'nombre' => 'ZAMBRANO'],

            // Boyacá (15)
            ['cod_dep' => '15', 'codigo' => '15001', 'nombre' => 'TUNJA'],
            ['cod_dep' => '15', 'codigo' => '15022', 'nombre' => 'ALMEIDA'],
            ['cod_dep' => '15', 'codigo' => '15047', 'nombre' => 'AQUITANIA'],
            ['cod_dep' => '15', 'codigo' => '15051', 'nombre' => 'ARCABUCO'],
            ['cod_dep' => '15', 'codigo' => '15087', 'nombre' => 'BELÉN'],
            ['cod_dep' => '15', 'codigo' => '15090', 'nombre' => 'BERBEO'],
            ['cod_dep' => '15', 'codigo' => '15092', 'nombre' => 'BETÉITIVA'],
            ['cod_dep' => '15', 'codigo' => '15097', 'nombre' => 'BOAVITA'],
            ['cod_dep' => '15', 'codigo' => '15104', 'nombre' => 'BOYACÁ'],
            ['cod_dep' => '15', 'codigo' => '15106', 'nombre' => 'BRICEÑO'],
            ['cod_dep' => '15', 'codigo' => '15109', 'nombre' => 'BUENAVISTA'],
            ['cod_dep' => '15', 'codigo' => '15114', 'nombre' => 'BUSBANZÁ'],
            ['cod_dep' => '15', 'codigo' => '15131', 'nombre' => 'CALDAS'],
            ['cod_dep' => '15', 'codigo' => '15135', 'nombre' => 'CAMPOHERMOSO'],
            ['cod_dep' => '15', 'codigo' => '15162', 'nombre' => 'CERINZA'],
            ['cod_dep' => '15', 'codigo' => '15172', 'nombre' => 'CHINAVITA'],
            ['cod_dep' => '15', 'codigo' => '15176', 'nombre' => 'CHIQUINQUIRÁ'],
            ['cod_dep' => '15', 'codigo' => '15180', 'nombre' => 'CHISCAS'],
            ['cod_dep' => '15', 'codigo' => '15183', 'nombre' => 'CHITA'],
            ['cod_dep' => '15', 'codigo' => '15185', 'nombre' => 'CHITARAQUE'],
            ['cod_dep' => '15', 'codigo' => '15187', 'nombre' => 'CHIVATÁ'],
            ['cod_dep' => '15', 'codigo' => '15189', 'nombre' => 'CIÉNEGA'],
            ['cod_dep' => '15', 'codigo' => '15204', 'nombre' => 'CÓMBITA'],
            ['cod_dep' => '15', 'codigo' => '15212', 'nombre' => 'COPER'],
            ['cod_dep' => '15', 'codigo' => '15215', 'nombre' => 'CORRALES'],
            ['cod_dep' => '15', 'codigo' => '15218', 'nombre' => 'COVARACHÍA'],
            ['cod_dep' => '15', 'codigo' => '15223', 'nombre' => 'CUBARÁ'],
            ['cod_dep' => '15', 'codigo' => '15224', 'nombre' => 'CUCAITA'],
            ['cod_dep' => '15', 'codigo' => '15226', 'nombre' => 'CUÍTIVA'],
            ['cod_dep' => '15', 'codigo' => '15232', 'nombre' => 'CHÍQUIZA'],
            ['cod_dep' => '15', 'codigo' => '15236', 'nombre' => 'CHIVOR'],
            ['cod_dep' => '15', 'codigo' => '15238', 'nombre' => 'DUITAMA'],
            ['cod_dep' => '15', 'codigo' => '15244', 'nombre' => 'EL COCUY'],
            ['cod_dep' => '15', 'codigo' => '15248', 'nombre' => 'EL ESPINO'],
            ['cod_dep' => '15', 'codigo' => '15272', 'nombre' => 'FIRAVITOBA'],
            ['cod_dep' => '15', 'codigo' => '15276', 'nombre' => 'FLORESTA'],
            ['cod_dep' => '15', 'codigo' => '15293', 'nombre' => 'GACHANTIVÁ'],
            ['cod_dep' => '15', 'codigo' => '15296', 'nombre' => 'GÁMEZA'],
            ['cod_dep' => '15', 'codigo' => '15299', 'nombre' => 'GARAGOA'],
            ['cod_dep' => '15', 'codigo' => '15317', 'nombre' => 'GUACAMAYAS'],
            ['cod_dep' => '15', 'codigo' => '15322', 'nombre' => 'GUATEQUE'],
            ['cod_dep' => '15', 'codigo' => '15325', 'nombre' => 'GUAYATÁ'],
            ['cod_dep' => '15', 'codigo' => '15332', 'nombre' => 'GÜICÁN DE LA SIERRA'],
            ['cod_dep' => '15', 'codigo' => '15362', 'nombre' => 'IZA'],
            ['cod_dep' => '15', 'codigo' => '15367', 'nombre' => 'JENESANO'],
            ['cod_dep' => '15', 'codigo' => '15368', 'nombre' => 'JERICÓ'],
            ['cod_dep' => '15', 'codigo' => '15377', 'nombre' => 'LABRANZAGRANDE'],
            ['cod_dep' => '15', 'codigo' => '15380', 'nombre' => 'LA CAPILLA'],
            ['cod_dep' => '15', 'codigo' => '15401', 'nombre' => 'LA VICTORIA'],
            ['cod_dep' => '15', 'codigo' => '15403', 'nombre' => 'LA UVITA'],
            ['cod_dep' => '15', 'codigo' => '15407', 'nombre' => 'VILLA DE LEYVA'],
            ['cod_dep' => '15', 'codigo' => '15425', 'nombre' => 'MACANAL'],
            ['cod_dep' => '15', 'codigo' => '15442', 'nombre' => 'MARIPÍ'],
            ['cod_dep' => '15', 'codigo' => '15455', 'nombre' => 'MIRAFLORES'],
            ['cod_dep' => '15', 'codigo' => '15464', 'nombre' => 'MONGUA'],
            ['cod_dep' => '15', 'codigo' => '15466', 'nombre' => 'MONGUÍ'],
            ['cod_dep' => '15', 'codigo' => '15469', 'nombre' => 'MONIQUIRÁ'],
            ['cod_dep' => '15', 'codigo' => '15476', 'nombre' => 'MOTAVITA'],
            ['cod_dep' => '15', 'codigo' => '15480', 'nombre' => 'MUZO'],
            ['cod_dep' => '15', 'codigo' => '15491', 'nombre' => 'NOBSA'],
            ['cod_dep' => '15', 'codigo' => '15494', 'nombre' => 'NUEVO COLÓN'],
            ['cod_dep' => '15', 'codigo' => '15500', 'nombre' => 'OICATÁ'],
            ['cod_dep' => '15', 'codigo' => '15507', 'nombre' => 'OTANCHE'],
            ['cod_dep' => '15', 'codigo' => '15511', 'nombre' => 'PACHAVITA'],
            ['cod_dep' => '15', 'codigo' => '15514', 'nombre' => 'PÁEZ'],
            ['cod_dep' => '15', 'codigo' => '15516', 'nombre' => 'PAIPA'],
            ['cod_dep' => '15', 'codigo' => '15518', 'nombre' => 'PAJARITO'],
            ['cod_dep' => '15', 'codigo' => '15522', 'nombre' => 'PANQUEBA'],
            ['cod_dep' => '15', 'codigo' => '15531', 'nombre' => 'PAUNA'],
            ['cod_dep' => '15', 'codigo' => '15533', 'nombre' => 'PAYA'],
            ['cod_dep' => '15', 'codigo' => '15537', 'nombre' => 'PAZ DE RÍO'],
            ['cod_dep' => '15', 'codigo' => '15542', 'nombre' => 'PESCA'],
            ['cod_dep' => '15', 'codigo' => '15550', 'nombre' => 'PISBA'],
            ['cod_dep' => '15', 'codigo' => '15572', 'nombre' => 'PUERTO BOYACÁ'],
            ['cod_dep' => '15', 'codigo' => '15580', 'nombre' => 'QUÍPAMA'],
            ['cod_dep' => '15', 'codigo' => '15599', 'nombre' => 'RAMIRIQUÍ'],
            ['cod_dep' => '15', 'codigo' => '15600', 'nombre' => 'RÁQUIRA'],
            ['cod_dep' => '15', 'codigo' => '15621', 'nombre' => 'RONDÓN'],
            ['cod_dep' => '15', 'codigo' => '15632', 'nombre' => 'SABOYÁ'],
            ['cod_dep' => '15', 'codigo' => '15638', 'nombre' => 'SÁCHICA'],
            ['cod_dep' => '15', 'codigo' => '15646', 'nombre' => 'SAMACÁ'],
            ['cod_dep' => '15', 'codigo' => '15660', 'nombre' => 'SAN EDUARDO'],
            ['cod_dep' => '15', 'codigo' => '15664', 'nombre' => 'SAN JOSÉ DE PARE'],
            ['cod_dep' => '15', 'codigo' => '15667', 'nombre' => 'SAN LUIS DE GACENO'],
            ['cod_dep' => '15', 'codigo' => '15673', 'nombre' => 'SAN MATEO'],
            ['cod_dep' => '15', 'codigo' => '15676', 'nombre' => 'SAN MIGUEL DE SEMA'],
            ['cod_dep' => '15', 'codigo' => '15681', 'nombre' => 'SAN PABLO DE BORBUR'],
            ['cod_dep' => '15', 'codigo' => '15686', 'nombre' => 'SANTANA'],
            ['cod_dep' => '15', 'codigo' => '15690', 'nombre' => 'SANTA MARÍA'],
            ['cod_dep' => '15', 'codigo' => '15693', 'nombre' => 'SANTA ROSA DE VITERBO'],
            ['cod_dep' => '15', 'codigo' => '15696', 'nombre' => 'SANTA SOFÍA'],
            ['cod_dep' => '15', 'codigo' => '15720', 'nombre' => 'SATIVANORTE'],
            ['cod_dep' => '15', 'codigo' => '15723', 'nombre' => 'SATIVASUR'],
            ['cod_dep' => '15', 'codigo' => '15740', 'nombre' => 'SIACHOQUE'],
            ['cod_dep' => '15', 'codigo' => '15753', 'nombre' => 'SOATÁ'],
            ['cod_dep' => '15', 'codigo' => '15755', 'nombre' => 'SOCOTÁ'],
            ['cod_dep' => '15', 'codigo' => '15757', 'nombre' => 'SOCHA'],
            ['cod_dep' => '15', 'codigo' => '15759', 'nombre' => 'SOGAMOSO'],
            ['cod_dep' => '15', 'codigo' => '15761', 'nombre' => 'SOMONDOCO'],
            ['cod_dep' => '15', 'codigo' => '15762', 'nombre' => 'SORA'],
            ['cod_dep' => '15', 'codigo' => '15763', 'nombre' => 'SOTAQUIRÁ'],
            ['cod_dep' => '15', 'codigo' => '15764', 'nombre' => 'SORACÁ'],
            ['cod_dep' => '15', 'codigo' => '15774', 'nombre' => 'SUSACÓN'],
            ['cod_dep' => '15', 'codigo' => '15776', 'nombre' => 'SUTAMARCHÁN'],
            ['cod_dep' => '15', 'codigo' => '15778', 'nombre' => 'SUTATENZA'],
            ['cod_dep' => '15', 'codigo' => '15790', 'nombre' => 'TASCO'],
            ['cod_dep' => '15', 'codigo' => '15798', 'nombre' => 'TENZA'],
            ['cod_dep' => '15', 'codigo' => '15804', 'nombre' => 'TIBANÁ'],
            ['cod_dep' => '15', 'codigo' => '15806', 'nombre' => 'TIBASOSA'],
            ['cod_dep' => '15', 'codigo' => '15808', 'nombre' => 'TINJACÁ'],
            ['cod_dep' => '15', 'codigo' => '15810', 'nombre' => 'TIPACOQUE'],
            ['cod_dep' => '15', 'codigo' => '15814', 'nombre' => 'TOCA'],
            ['cod_dep' => '15', 'codigo' => '15816', 'nombre' => 'TOGÜÍ'],
            ['cod_dep' => '15', 'codigo' => '15820', 'nombre' => 'TÓPAGA'],
            ['cod_dep' => '15', 'codigo' => '15822', 'nombre' => 'TOTA'],
            ['cod_dep' => '15', 'codigo' => '15832', 'nombre' => 'TUNUNGUÁ'],
            ['cod_dep' => '15', 'codigo' => '15835', 'nombre' => 'TURMEQUÉ'],
            ['cod_dep' => '15', 'codigo' => '15837', 'nombre' => 'TUTA'],
            ['cod_dep' => '15', 'codigo' => '15839', 'nombre' => 'TUTAZÁ'],
            ['cod_dep' => '15', 'codigo' => '15842', 'nombre' => 'ÚMBITA'],
            ['cod_dep' => '15', 'codigo' => '15861', 'nombre' => 'VENTAQUEMADA'],
            ['cod_dep' => '15', 'codigo' => '15879', 'nombre' => 'VIRACACHÁ'],
            ['cod_dep' => '15', 'codigo' => '15897', 'nombre' => 'ZETAQUIRA'],

        ];
        
        // Caldas (17), Caquetá (18), Casanare (85), Cauca (19)
        $batch3 = [
            // Caldas (17)
            ['cod_dep' => '17', 'codigo' => '17001', 'nombre' => 'MANIZALES'],
            ['cod_dep' => '17', 'codigo' => '17013', 'nombre' => 'AGUADAS'],
            ['cod_dep' => '17', 'codigo' => '17042', 'nombre' => 'ANSERMA'],
            ['cod_dep' => '17', 'codigo' => '17050', 'nombre' => 'ARANZAZU'],
            ['cod_dep' => '17', 'codigo' => '17088', 'nombre' => 'BELALCÁZAR'],
            ['cod_dep' => '17', 'codigo' => '17174', 'nombre' => 'CHINCHINÁ'],
            ['cod_dep' => '17', 'codigo' => '17272', 'nombre' => 'FILADELFIA'],
            ['cod_dep' => '17', 'codigo' => '17380', 'nombre' => 'LA DORADA'],
            ['cod_dep' => '17', 'codigo' => '17388', 'nombre' => 'LA MERCED'],
            ['cod_dep' => '17', 'codigo' => '17433', 'nombre' => 'MANZANARES'],
            ['cod_dep' => '17', 'codigo' => '17442', 'nombre' => 'MARMATO'],
            ['cod_dep' => '17', 'codigo' => '17444', 'nombre' => 'MARQUETALIA'],
            ['cod_dep' => '17', 'codigo' => '17446', 'nombre' => 'MARULANDA'],
            ['cod_dep' => '17', 'codigo' => '17486', 'nombre' => 'NEIRA'],
            ['cod_dep' => '17', 'codigo' => '17495', 'nombre' => 'NORCASIA'],
            ['cod_dep' => '17', 'codigo' => '17513', 'nombre' => 'PÁCORA'],
            ['cod_dep' => '17', 'codigo' => '17524', 'nombre' => 'PALESTINA'],
            ['cod_dep' => '17', 'codigo' => '17541', 'nombre' => 'PENSILVANIA'],
            ['cod_dep' => '17', 'codigo' => '17614', 'nombre' => 'RIOSUCIO'],
            ['cod_dep' => '17', 'codigo' => '17616', 'nombre' => 'RISARALDA'],
            ['cod_dep' => '17', 'codigo' => '17653', 'nombre' => 'SALAMINA'],
            ['cod_dep' => '17', 'codigo' => '17662', 'nombre' => 'SAMANÁ'],
            ['cod_dep' => '17', 'codigo' => '17665', 'nombre' => 'SAN JOSÉ'],
            ['cod_dep' => '17', 'codigo' => '17777', 'nombre' => 'SUPÍA'],
            ['cod_dep' => '17', 'codigo' => '17867', 'nombre' => 'VICTORIA'],
            ['cod_dep' => '17', 'codigo' => '17873', 'nombre' => 'VILLAMARÍA'],
            ['cod_dep' => '17', 'codigo' => '17877', 'nombre' => 'VITERBO'],

            // Caquetá (18)
            ['cod_dep' => '18', 'codigo' => '18001', 'nombre' => 'FLORENCIA'],
            ['cod_dep' => '18', 'codigo' => '18029', 'nombre' => 'ALBANIA'],
            ['cod_dep' => '18', 'codigo' => '18094', 'nombre' => 'BELÉN DE LOS ANDAQUÍES'],
            ['cod_dep' => '18', 'codigo' => '18150', 'nombre' => 'CARTAGENA DEL CHAIRÁ'],
            ['cod_dep' => '18', 'codigo' => '18205', 'nombre' => 'CURILLO'],
            ['cod_dep' => '18', 'codigo' => '18247', 'nombre' => 'EL DONCELLO'],
            ['cod_dep' => '18', 'codigo' => '18256', 'nombre' => 'EL PAUJÍL'],
            ['cod_dep' => '18', 'codigo' => '18410', 'nombre' => 'LA MONTAÑITA'],
            ['cod_dep' => '18', 'codigo' => '18460', 'nombre' => 'MILÁN'],
            ['cod_dep' => '18', 'codigo' => '18479', 'nombre' => 'MORELIA'],
            ['cod_dep' => '18', 'codigo' => '18592', 'nombre' => 'PUERTO RICO'],
            ['cod_dep' => '18', 'codigo' => '18610', 'nombre' => 'SAN JOSÉ DEL FRAGUA'],
            ['cod_dep' => '18', 'codigo' => '18753', 'nombre' => 'SAN VICENTE DEL CAGUÁN'],
            ['cod_dep' => '18', 'codigo' => '18756', 'nombre' => 'SOLANO'],
            ['cod_dep' => '18', 'codigo' => '18785', 'nombre' => 'SOLITA'],
            ['cod_dep' => '18', 'codigo' => '18860', 'nombre' => 'VALPARAÍSO'],

            // Casanare (85)
            ['cod_dep' => '85', 'codigo' => '85001', 'nombre' => 'YOPAL'],
            ['cod_dep' => '85', 'codigo' => '85010', 'nombre' => 'AGUAZUL'],
            ['cod_dep' => '85', 'codigo' => '85015', 'nombre' => 'CHÁMEZA'],
            ['cod_dep' => '85', 'codigo' => '85125', 'nombre' => 'HATO COROZAL'],
            ['cod_dep' => '85', 'codigo' => '85136', 'nombre' => 'LA SALINA'],
            ['cod_dep' => '85', 'codigo' => '85139', 'nombre' => 'MANÍ'],
            ['cod_dep' => '85', 'codigo' => '85162', 'nombre' => 'MONTERREY'],
            ['cod_dep' => '85', 'codigo' => '85225', 'nombre' => 'NUNCHÍA'],
            ['cod_dep' => '85', 'codigo' => '85230', 'nombre' => 'OROCUÉ'],
            ['cod_dep' => '85', 'codigo' => '85250', 'nombre' => 'PAZ DE ARIPORO'],
            ['cod_dep' => '85', 'codigo' => '85263', 'nombre' => 'PORE'],
            ['cod_dep' => '85', 'codigo' => '85279', 'nombre' => 'RECETOR'],
            ['cod_dep' => '85', 'codigo' => '85300', 'nombre' => 'SABANALARGA'],
            ['cod_dep' => '85', 'codigo' => '85315', 'nombre' => 'SÁCAMA'],
            ['cod_dep' => '85', 'codigo' => '85325', 'nombre' => 'SAN LUIS DE PALENQUE'],
            ['cod_dep' => '85', 'codigo' => '85400', 'nombre' => 'TÁMARA'],
            ['cod_dep' => '85', 'codigo' => '85410', 'nombre' => 'TAURAMENA'],
            ['cod_dep' => '85', 'codigo' => '85430', 'nombre' => 'TRINIDAD'],
            ['cod_dep' => '85', 'codigo' => '85440', 'nombre' => 'VILLANUEVA'],

            // Cesar (20) - Wait, input said Cesar (20) in the list after Cauca in the text provided but the request title only said "caldas caqueta casanare y caldas" but the body had Cesar and Choco. Let me re-read the request.
            // Re-reading user request: "ahora vamos con caldas caqueta casanare y caldas"
            // The text block pasted contains: Caldas, Caqueta, Casanare, Cauca, Cesar, Choco, Cordoba, Cundinamarca.
            // The user PASTED a huge block. I should assume they want ALL of it processed.
            // Okay, let's look at the pasted text more carefully.
            // It goes from Caldas (17) ... to Cundinamarca (25).
            // I will process ALL of it.
            
            // Cauca (19)
            ['cod_dep' => '19', 'codigo' => '19001', 'nombre' => 'POPAYÁN'],
            ['cod_dep' => '19', 'codigo' => '19022', 'nombre' => 'ALMAGUER'],
            ['cod_dep' => '19', 'codigo' => '19050', 'nombre' => 'ARGELIA'],
            ['cod_dep' => '19', 'codigo' => '19075', 'nombre' => 'BALBOA'],
            ['cod_dep' => '19', 'codigo' => '19100', 'nombre' => 'BOLÍVAR'],
            ['cod_dep' => '19', 'codigo' => '19110', 'nombre' => 'BUENOS AIRES'],
            ['cod_dep' => '19', 'codigo' => '19130', 'nombre' => 'CAJIBÍO'],
            ['cod_dep' => '19', 'codigo' => '19137', 'nombre' => 'CALDONO'],
            ['cod_dep' => '19', 'codigo' => '19142', 'nombre' => 'CALOTO'],
            ['cod_dep' => '19', 'codigo' => '19212', 'nombre' => 'CORINTO'],
            ['cod_dep' => '19', 'codigo' => '19256', 'nombre' => 'EL TAMBO'],
            ['cod_dep' => '19', 'codigo' => '19290', 'nombre' => 'FLORENCIA'],
            ['cod_dep' => '19', 'codigo' => '19300', 'nombre' => 'GUACHENÉ'],
            ['cod_dep' => '19', 'codigo' => '19318', 'nombre' => 'GUAPÍ'],
            ['cod_dep' => '19', 'codigo' => '19355', 'nombre' => 'INZÁ'],
            ['cod_dep' => '19', 'codigo' => '19364', 'nombre' => 'JAMBALÓ'],
            ['cod_dep' => '19', 'codigo' => '19392', 'nombre' => 'LA SIERRA'],
            ['cod_dep' => '19', 'codigo' => '19397', 'nombre' => 'LA VEGA'],
            ['cod_dep' => '19', 'codigo' => '19418', 'nombre' => 'LÓPEZ DE MICAY'],
            ['cod_dep' => '19', 'codigo' => '19450', 'nombre' => 'MERCADERES'],
            ['cod_dep' => '19', 'codigo' => '19455', 'nombre' => 'MIRANDA'],
            ['cod_dep' => '19', 'codigo' => '19473', 'nombre' => 'MORALES'],
            ['cod_dep' => '19', 'codigo' => '19513', 'nombre' => 'PADILLA'],
            ['cod_dep' => '19', 'codigo' => '19517', 'nombre' => 'PÁEZ ‐ BELALCAZAR'],
            ['cod_dep' => '19', 'codigo' => '19532', 'nombre' => 'PATÍA – EL BORDO'],
            ['cod_dep' => '19', 'codigo' => '19533', 'nombre' => 'PIAMONTE'],
            ['cod_dep' => '19', 'codigo' => '19548', 'nombre' => 'PIENDAMÓ – TUNÍA'],
            ['cod_dep' => '19', 'codigo' => '19573', 'nombre' => 'PUERTO TEJADA'],
            ['cod_dep' => '19', 'codigo' => '19585', 'nombre' => 'PURACÉ ‐ COCONUCO'],
            ['cod_dep' => '19', 'codigo' => '19622', 'nombre' => 'ROSAS'],
            ['cod_dep' => '19', 'codigo' => '19693', 'nombre' => 'SAN SEBASTIÁN'],
            ['cod_dep' => '19', 'codigo' => '19698', 'nombre' => 'SANTANDER DE QUILICHAO'],
            ['cod_dep' => '19', 'codigo' => '19701', 'nombre' => 'SANTA ROSA'],
            ['cod_dep' => '19', 'codigo' => '19743', 'nombre' => 'SILVIA'],
            ['cod_dep' => '19', 'codigo' => '19760', 'nombre' => 'SOTARA'],
            ['cod_dep' => '19', 'codigo' => '19780', 'nombre' => 'SUÁREZ'],
            ['cod_dep' => '19', 'codigo' => '19785', 'nombre' => 'SUCRE'],
            ['cod_dep' => '19', 'codigo' => '19807', 'nombre' => 'TIMBÍO'],
            ['cod_dep' => '19', 'codigo' => '19809', 'nombre' => 'TIMBIQUÍ'],
            ['cod_dep' => '19', 'codigo' => '19821', 'nombre' => 'TORIBÍO'],
            ['cod_dep' => '19', 'codigo' => '19824', 'nombre' => 'TOTORÓ'],
            ['cod_dep' => '19', 'codigo' => '19845', 'nombre' => 'VILLA RICA'],

            // Cesar (20)
            ['cod_dep' => '20', 'codigo' => '20001', 'nombre' => 'VALLEDUPAR'],
            ['cod_dep' => '20', 'codigo' => '20011', 'nombre' => 'AGUACHICA'],
            ['cod_dep' => '20', 'codigo' => '20013', 'nombre' => 'AGUSTÍN CODAZZI'],
            ['cod_dep' => '20', 'codigo' => '20032', 'nombre' => 'ASTREA'],
            ['cod_dep' => '20', 'codigo' => '20045', 'nombre' => 'BECERRIL'],
            ['cod_dep' => '20', 'codigo' => '20060', 'nombre' => 'BOSCONIA'],
            ['cod_dep' => '20', 'codigo' => '20175', 'nombre' => 'CHIMICHAGUA'],
            ['cod_dep' => '20', 'codigo' => '20178', 'nombre' => 'CHIRIGUANÁ'],
            ['cod_dep' => '20', 'codigo' => '20228', 'nombre' => 'CURUMANÍ'],
            ['cod_dep' => '20', 'codigo' => '20238', 'nombre' => 'EL COPEY'],
            ['cod_dep' => '20', 'codigo' => '20250', 'nombre' => 'EL PASO'],
            ['cod_dep' => '20', 'codigo' => '20295', 'nombre' => 'GAMARRA'],
            ['cod_dep' => '20', 'codigo' => '20310', 'nombre' => 'GONZÁLEZ'],
            ['cod_dep' => '20', 'codigo' => '20383', 'nombre' => 'LA GLORIA'],
            ['cod_dep' => '20', 'codigo' => '20400', 'nombre' => 'LA JAGUA DE IBIRICO'],
            ['cod_dep' => '20', 'codigo' => '20443', 'nombre' => 'MANAURE BALCÓN DEL CESAR'],
            ['cod_dep' => '20', 'codigo' => '20517', 'nombre' => 'PAILITAS'],
            ['cod_dep' => '20', 'codigo' => '20550', 'nombre' => 'PELAYA'],
            ['cod_dep' => '20', 'codigo' => '20570', 'nombre' => 'PUEBLO BELLO'],
            ['cod_dep' => '20', 'codigo' => '20614', 'nombre' => 'RÍO DE ORO'],
            ['cod_dep' => '20', 'codigo' => '20621', 'nombre' => 'LA PAZ'],
            ['cod_dep' => '20', 'codigo' => '20710', 'nombre' => 'SAN ALBERTO'],
            ['cod_dep' => '20', 'codigo' => '20750', 'nombre' => 'SAN DIEGO'],
            ['cod_dep' => '20', 'codigo' => '20770', 'nombre' => 'SAN MARTÍN'],
            ['cod_dep' => '20', 'codigo' => '20787', 'nombre' => 'TAMALAMEQUE'],

            // Chocó (27)
            ['cod_dep' => '27', 'codigo' => '27001', 'nombre' => 'QUIBDÓ'],
            ['cod_dep' => '27', 'codigo' => '27006', 'nombre' => 'ACANDÍ'],
            ['cod_dep' => '27', 'codigo' => '27025', 'nombre' => 'ALTO BAUDÓ (PIE DE PATÓ)'],
            ['cod_dep' => '27', 'codigo' => '27050', 'nombre' => 'ATRATO (YUTO)'],
            ['cod_dep' => '27', 'codigo' => '27073', 'nombre' => 'BAGADÓ'],
            ['cod_dep' => '27', 'codigo' => '27075', 'nombre' => 'BAHÍA SOLANO (MUTIS)'],
            ['cod_dep' => '27', 'codigo' => '27077', 'nombre' => 'BAJO BAUDÓ (PIZARRO)'],
            ['cod_dep' => '27', 'codigo' => '27099', 'nombre' => 'BOJAYÁ (BELLA VISTA)'],
            ['cod_dep' => '27', 'codigo' => '27135', 'nombre' => 'EL CANTÓN DEL SAN PABLO'],
            ['cod_dep' => '27', 'codigo' => '27150', 'nombre' => 'CARMEN DEL DARIÉN'],
            ['cod_dep' => '27', 'codigo' => '27160', 'nombre' => 'CÉRTEGUI'],
            ['cod_dep' => '27', 'codigo' => '27205', 'nombre' => 'CONDOTO'],
            ['cod_dep' => '27', 'codigo' => '27245', 'nombre' => 'EL CARMEN DE ATRATO'],
            ['cod_dep' => '27', 'codigo' => '27250', 'nombre' => 'EL LITORAL DEL SAN JUAN'],
            ['cod_dep' => '27', 'codigo' => '27361', 'nombre' => 'ISTMINA'],
            ['cod_dep' => '27', 'codigo' => '27372', 'nombre' => 'JURADÓ'],
            ['cod_dep' => '27', 'codigo' => '27413', 'nombre' => 'LLORÓ'],
            ['cod_dep' => '27', 'codigo' => '27425', 'nombre' => 'MEDIO ATRATO (BETÉ)'],
            ['cod_dep' => '27', 'codigo' => '27430', 'nombre' => 'MEDIO BAUDÓ'],
            ['cod_dep' => '27', 'codigo' => '27450', 'nombre' => 'MEDIO SAN JUAN (ANDAGOYA)'],
            ['cod_dep' => '27', 'codigo' => '27491', 'nombre' => 'NÓVITA'],
            ['cod_dep' => '27', 'codigo' => '27495', 'nombre' => 'NUQUÍ'],
            ['cod_dep' => '27', 'codigo' => '27580', 'nombre' => 'RÍO IRÓ (SANTA RITA)'],
            ['cod_dep' => '27', 'codigo' => '27600', 'nombre' => 'RÍO QUITO (PAIMADÓ)'],
            ['cod_dep' => '27', 'codigo' => '27615', 'nombre' => 'RIOSUCIO'],
            ['cod_dep' => '27', 'codigo' => '27660', 'nombre' => 'SAN JOSÉ DEL PALMAR'],
            ['cod_dep' => '27', 'codigo' => '27745', 'nombre' => 'SIPÍ'],
            ['cod_dep' => '27', 'codigo' => '27787', 'nombre' => 'TADÓ'],
            ['cod_dep' => '27', 'codigo' => '27800', 'nombre' => 'UNGUÍA'],
            ['cod_dep' => '27', 'codigo' => '27810', 'nombre' => 'UNIÓN PANAMERICANA (LAS ÁNIMAS)'],

            // Córdoba (23)
            ['cod_dep' => '23', 'codigo' => '23001', 'nombre' => 'MONTERÍA'],
            ['cod_dep' => '23', 'codigo' => '23068', 'nombre' => 'AYAPEL'],
            ['cod_dep' => '23', 'codigo' => '23079', 'nombre' => 'BUENAVISTA'],
            ['cod_dep' => '23', 'codigo' => '23090', 'nombre' => 'CANALETE'],
            ['cod_dep' => '23', 'codigo' => '23162', 'nombre' => 'CERETÉ'],
            ['cod_dep' => '23', 'codigo' => '23168', 'nombre' => 'CHIMÁ'],
            ['cod_dep' => '23', 'codigo' => '23182', 'nombre' => 'CHINÚ'],
            ['cod_dep' => '23', 'codigo' => '23189', 'nombre' => 'CIÉNAGA DE ORO'],
            ['cod_dep' => '23', 'codigo' => '23300', 'nombre' => 'COTORRA'],
            ['cod_dep' => '23', 'codigo' => '23350', 'nombre' => 'LA APARTADA'],
            ['cod_dep' => '23', 'codigo' => '23417', 'nombre' => 'LORICA'],
            ['cod_dep' => '23', 'codigo' => '23419', 'nombre' => 'LOS CÓRDOBAS'],
            ['cod_dep' => '23', 'codigo' => '23464', 'nombre' => 'MOMIL'],
            ['cod_dep' => '23', 'codigo' => '23466', 'nombre' => 'MONTELÍBANO'],
            ['cod_dep' => '23', 'codigo' => '23500', 'nombre' => 'MOÑITOS'],
            ['cod_dep' => '23', 'codigo' => '23555', 'nombre' => 'PLANETA RICA'],
            ['cod_dep' => '23', 'codigo' => '23570', 'nombre' => 'PUEBLO NUEVO'],
            ['cod_dep' => '23', 'codigo' => '23574', 'nombre' => 'PUERTO ESCONDIDO'],
            ['cod_dep' => '23', 'codigo' => '23580', 'nombre' => 'PUERTO LIBERTADOR'],
            ['cod_dep' => '23', 'codigo' => '23586', 'nombre' => 'PURÍSIMA DE LA CONCEPCIÓN'],
            ['cod_dep' => '23', 'codigo' => '23660', 'nombre' => 'SAHAGÚN'],
            ['cod_dep' => '23', 'codigo' => '23670', 'nombre' => 'SAN ANDRÉS DE SOTAVENTO'],
            ['cod_dep' => '23', 'codigo' => '23672', 'nombre' => 'SAN ANTERO'],
            ['cod_dep' => '23', 'codigo' => '23675', 'nombre' => 'SAN BERNARDO DEL VIENTO'],
            ['cod_dep' => '23', 'codigo' => '23678', 'nombre' => 'SAN CARLOS'],
            ['cod_dep' => '23', 'codigo' => '23682', 'nombre' => 'SAN JOSÉ DE URÉ'],
            ['cod_dep' => '23', 'codigo' => '23686', 'nombre' => 'SAN PELAYO'],
            ['cod_dep' => '23', 'codigo' => '23807', 'nombre' => 'TIERRALTA'],
            ['cod_dep' => '23', 'codigo' => '23815', 'nombre' => 'TUCHÍN'],
            ['cod_dep' => '23', 'codigo' => '23855', 'nombre' => 'VALENCIA'],

            // Cundinamarca (25)
            ['cod_dep' => '25', 'codigo' => '25001', 'nombre' => 'AGUA DE DIOS'],
            ['cod_dep' => '25', 'codigo' => '25019', 'nombre' => 'ALBÁN'],
            ['cod_dep' => '25', 'codigo' => '25035', 'nombre' => 'ANAPOIMA'],
            ['cod_dep' => '25', 'codigo' => '25040', 'nombre' => 'ANOLAIMA'],
            ['cod_dep' => '25', 'codigo' => '25053', 'nombre' => 'ARBELÁEZ'],
            ['cod_dep' => '25', 'codigo' => '25086', 'nombre' => 'BELTRÁN'],
            ['cod_dep' => '25', 'codigo' => '25095', 'nombre' => 'BITUIMA'],
            ['cod_dep' => '25', 'codigo' => '25099', 'nombre' => 'BOJACÁ'],
            ['cod_dep' => '25', 'codigo' => '25120', 'nombre' => 'CABRERA'],
            ['cod_dep' => '25', 'codigo' => '25123', 'nombre' => 'CACHIPAY'],
            ['cod_dep' => '25', 'codigo' => '25126', 'nombre' => 'CAJICÁ'],
            ['cod_dep' => '25', 'codigo' => '25148', 'nombre' => 'CAPARRAPÍ'],
            ['cod_dep' => '25', 'codigo' => '25151', 'nombre' => 'CÁQUEZA'],
            ['cod_dep' => '25', 'codigo' => '25154', 'nombre' => 'CARMEN DE CARUPA'],
            ['cod_dep' => '25', 'codigo' => '25168', 'nombre' => 'CHAGUANÍ'],
            ['cod_dep' => '25', 'codigo' => '25175', 'nombre' => 'CHÍA'],
            ['cod_dep' => '25', 'codigo' => '25178', 'nombre' => 'CHIPAQUE'],
            ['cod_dep' => '25', 'codigo' => '25181', 'nombre' => 'CHOACHÍ'],
            ['cod_dep' => '25', 'codigo' => '25183', 'nombre' => 'CHOCONTÁ'],
            ['cod_dep' => '25', 'codigo' => '25200', 'nombre' => 'COGUA'],
            ['cod_dep' => '25', 'codigo' => '25214', 'nombre' => 'COTA'],
            ['cod_dep' => '25', 'codigo' => '25224', 'nombre' => 'CUCUNUBÁ'],
            ['cod_dep' => '25', 'codigo' => '25245', 'nombre' => 'EL COLEGIO'],
            ['cod_dep' => '25', 'codigo' => '25258', 'nombre' => 'EL PEÑÓN'],
            ['cod_dep' => '25', 'codigo' => '25260', 'nombre' => 'EL ROSAL'],
            ['cod_dep' => '25', 'codigo' => '25269', 'nombre' => 'FACATATIVÁ'],
            ['cod_dep' => '25', 'codigo' => '25279', 'nombre' => 'FÓMEQUE'],
            ['cod_dep' => '25', 'codigo' => '25281', 'nombre' => 'FOSCA'],
            ['cod_dep' => '25', 'codigo' => '25286', 'nombre' => 'FUNZA'],
            ['cod_dep' => '25', 'codigo' => '25288', 'nombre' => 'FÚQUENE'],
            ['cod_dep' => '25', 'codigo' => '25290', 'nombre' => 'FUSAGASUGÁ'],
            ['cod_dep' => '25', 'codigo' => '25293', 'nombre' => 'GACHALÁ'],
            ['cod_dep' => '25', 'codigo' => '25295', 'nombre' => 'GACHANCIPÁ'],
            ['cod_dep' => '25', 'codigo' => '25297', 'nombre' => 'GACHETÁ'],
            ['cod_dep' => '25', 'codigo' => '25299', 'nombre' => 'GAMA'],
            ['cod_dep' => '25', 'codigo' => '25307', 'nombre' => 'GIRARDOT'],
            ['cod_dep' => '25', 'codigo' => '25312', 'nombre' => 'GRANADA'],
            ['cod_dep' => '25', 'codigo' => '25317', 'nombre' => 'GUACHETÁ'],
            ['cod_dep' => '25', 'codigo' => '25320', 'nombre' => 'GUADUAS'],
            ['cod_dep' => '25', 'codigo' => '25322', 'nombre' => 'GUASCA'],
            ['cod_dep' => '25', 'codigo' => '25324', 'nombre' => 'GUATAQUÍ'],
            ['cod_dep' => '25', 'codigo' => '25326', 'nombre' => 'GUATAVITA'],
            ['cod_dep' => '25', 'codigo' => '25328', 'nombre' => 'GUAYABAL DE SÍQUIMA'],
            ['cod_dep' => '25', 'codigo' => '25335', 'nombre' => 'GUAYABETAL'],
            ['cod_dep' => '25', 'codigo' => '25339', 'nombre' => 'GUTIÉRREZ'],
            ['cod_dep' => '25', 'codigo' => '25368', 'nombre' => 'JERUSALÉN'],
            ['cod_dep' => '25', 'codigo' => '25372', 'nombre' => 'JUNÍN'],
            ['cod_dep' => '25', 'codigo' => '25377', 'nombre' => 'LA CALERA'],
            ['cod_dep' => '25', 'codigo' => '25386', 'nombre' => 'LA MESA'],
            ['cod_dep' => '25', 'codigo' => '25394', 'nombre' => 'LA PALMA'],
            ['cod_dep' => '25', 'codigo' => '25398', 'nombre' => 'LA PEÑA'],
            ['cod_dep' => '25', 'codigo' => '25402', 'nombre' => 'LA VEGA'],
            ['cod_dep' => '25', 'codigo' => '25407', 'nombre' => 'LENGUAZAQUE'],
            ['cod_dep' => '25', 'codigo' => '25426', 'nombre' => 'MACHETÁ'],
            ['cod_dep' => '25', 'codigo' => '25430', 'nombre' => 'MADRID'],
            ['cod_dep' => '25', 'codigo' => '25436', 'nombre' => 'MANTA'],
            ['cod_dep' => '25', 'codigo' => '25438', 'nombre' => 'MEDINA'],
            ['cod_dep' => '25', 'codigo' => '25473', 'nombre' => 'MOSQUERA'],
            ['cod_dep' => '25', 'codigo' => '25483', 'nombre' => 'NARIÑO'],
            ['cod_dep' => '25', 'codigo' => '25486', 'nombre' => 'NEMOCÓN'],
            ['cod_dep' => '25', 'codigo' => '25488', 'nombre' => 'NILO'],
            ['cod_dep' => '25', 'codigo' => '25489', 'nombre' => 'NIMAIMA'],
            ['cod_dep' => '25', 'codigo' => '25491', 'nombre' => 'NOCAIMA'],
            ['cod_dep' => '25', 'codigo' => '25506', 'nombre' => 'VENECIA'],
            ['cod_dep' => '25', 'codigo' => '25513', 'nombre' => 'PACHO'],
            ['cod_dep' => '25', 'codigo' => '25518', 'nombre' => 'PAIME'],
            ['cod_dep' => '25', 'codigo' => '25524', 'nombre' => 'PANDI'],
            ['cod_dep' => '25', 'codigo' => '25530', 'nombre' => 'PARATEBUENO'],
            ['cod_dep' => '25', 'codigo' => '25535', 'nombre' => 'PASCA'],
            ['cod_dep' => '25', 'codigo' => '25572', 'nombre' => 'PUERTO SALGAR'],
            ['cod_dep' => '25', 'codigo' => '25580', 'nombre' => 'PULÍ'],
            ['cod_dep' => '25', 'codigo' => '25592', 'nombre' => 'QUEBRADANEGRA'],
            ['cod_dep' => '25', 'codigo' => '25594', 'nombre' => 'QUETAME'],
            ['cod_dep' => '25', 'codigo' => '25596', 'nombre' => 'QUIPILE'],
            ['cod_dep' => '25', 'codigo' => '25599', 'nombre' => 'APULO'],
            ['cod_dep' => '25', 'codigo' => '25612', 'nombre' => 'RICAURTE'],
            ['cod_dep' => '25', 'codigo' => '25645', 'nombre' => 'SAN ANTONIO DEL TEQUENDAMA'],
            ['cod_dep' => '25', 'codigo' => '25649', 'nombre' => 'SAN BERNARDO'],
            ['cod_dep' => '25', 'codigo' => '25653', 'nombre' => 'SAN CAYETANO'],
            ['cod_dep' => '25', 'codigo' => '25658', 'nombre' => 'SAN FRANCISCO'],
            ['cod_dep' => '25', 'codigo' => '25662', 'nombre' => 'SAN JUAN DE RIOSECO'],
            ['cod_dep' => '25', 'codigo' => '25718', 'nombre' => 'SASAIMA'],
            ['cod_dep' => '25', 'codigo' => '25736', 'nombre' => 'SESQUILÉ'],
            ['cod_dep' => '25', 'codigo' => '25740', 'nombre' => 'SIBATÉ'],
            ['cod_dep' => '25', 'codigo' => '25743', 'nombre' => 'SILVANIA'],
            ['cod_dep' => '25', 'codigo' => '25745', 'nombre' => 'SIMIJACA'],
            ['cod_dep' => '25', 'codigo' => '25754', 'nombre' => 'SOACHA'],
            ['cod_dep' => '25', 'codigo' => '25758', 'nombre' => 'SOPÓ'],
            ['cod_dep' => '25', 'codigo' => '25769', 'nombre' => 'SUBACHOQUE'],
            ['cod_dep' => '25', 'codigo' => '25772', 'nombre' => 'SUESCA'],
            ['cod_dep' => '25', 'codigo' => '25777', 'nombre' => 'SUPATÁ'],
            ['cod_dep' => '25', 'codigo' => '25779', 'nombre' => 'SUSA'],
            ['cod_dep' => '25', 'codigo' => '25781', 'nombre' => 'SUTATAUSA'],
            ['cod_dep' => '25', 'codigo' => '25785', 'nombre' => 'TABIO'],
            ['cod_dep' => '25', 'codigo' => '25793', 'nombre' => 'TAUSA'],
            ['cod_dep' => '25', 'codigo' => '25797', 'nombre' => 'TENA'],
            ['cod_dep' => '25', 'codigo' => '25799', 'nombre' => 'TENJO'],
            ['cod_dep' => '25', 'codigo' => '25805', 'nombre' => 'TIBACUY'],
            ['cod_dep' => '25', 'codigo' => '25807', 'nombre' => 'TIBIRITA'],
            ['cod_dep' => '25', 'codigo' => '25815', 'nombre' => 'TOCAIMA'],
            ['cod_dep' => '25', 'codigo' => '25817', 'nombre' => 'TOCANCIPÁ'],
            ['cod_dep' => '25', 'codigo' => '25823', 'nombre' => 'TOPAIPÍ'],
            ['cod_dep' => '25', 'codigo' => '25839', 'nombre' => 'UBALÁ'],
            ['cod_dep' => '25', 'codigo' => '25841', 'nombre' => 'UBAQUE'],
            ['cod_dep' => '25', 'codigo' => '25843', 'nombre' => 'VILLA DE SAN DIEGO DE UBATÉ'],
            ['cod_dep' => '25', 'codigo' => '25845', 'nombre' => 'UNE'],
            ['cod_dep' => '25', 'codigo' => '25851', 'nombre' => 'ÚTICA'],
            ['cod_dep' => '25', 'codigo' => '25862', 'nombre' => 'VERGARA'],
            ['cod_dep' => '25', 'codigo' => '25867', 'nombre' => 'VIANÍ'],
            ['cod_dep' => '25', 'codigo' => '25871', 'nombre' => 'VILLAGÓMEZ'],
            ['cod_dep' => '25', 'codigo' => '25873', 'nombre' => 'VILLAPINZÓN'],
            ['cod_dep' => '25', 'codigo' => '25875', 'nombre' => 'VILLETA'],
            ['cod_dep' => '25', 'codigo' => '25878', 'nombre' => 'VIOTÁ'],
            ['cod_dep' => '25', 'codigo' => '25885', 'nombre' => 'YACOPÍ'],
            ['cod_dep' => '25', 'codigo' => '25898', 'nombre' => 'ZIPACÓN'],
            ['cod_dep' => '25', 'codigo' => '25899', 'nombre' => 'ZIPAQUIRÁ'],
        ];

        // Guainía (94), Guaviare (95), Huila (41), La Guajira (44), Magdalena (47), Meta (50)
        $batch4 = [
            // Guainía (94)
            ['cod_dep' => '94', 'codigo' => '94001', 'nombre' => 'INÍRIDA'],
            ['cod_dep' => '94', 'codigo' => '94343', 'nombre' => 'BARRANCOMINAS'],
            ['cod_dep' => '94', 'codigo' => '94663', 'nombre' => 'MAPIRIPANA'],
            ['cod_dep' => '94', 'codigo' => '94883', 'nombre' => 'SAN FELIPE'],
            ['cod_dep' => '94', 'codigo' => '94884', 'nombre' => 'PUERTO COLOMBIA'],
            ['cod_dep' => '94', 'codigo' => '94885', 'nombre' => 'LA GUADALUPE'],
            ['cod_dep' => '94', 'codigo' => '94886', 'nombre' => 'CACAHUAL'],
            ['cod_dep' => '94', 'codigo' => '94887', 'nombre' => 'PANA PANA'],
            ['cod_dep' => '94', 'codigo' => '94888', 'nombre' => 'MORICHAL NUEVO'],

            // Guaviare (95)
            ['cod_dep' => '95', 'codigo' => '95001', 'nombre' => 'SAN JOSÉ DEL GUAVIARE'],
            ['cod_dep' => '95', 'codigo' => '95015', 'nombre' => 'CALAMAR'],
            ['cod_dep' => '95', 'codigo' => '95025', 'nombre' => 'EL RETORNO'],
            ['cod_dep' => '95', 'codigo' => '95200', 'nombre' => 'MIRAFLORES'],

            // Huila (41)
            ['cod_dep' => '41', 'codigo' => '41001', 'nombre' => 'NEIVA'],
            ['cod_dep' => '41', 'codigo' => '41006', 'nombre' => 'ACEVEDO'],
            ['cod_dep' => '41', 'codigo' => '41013', 'nombre' => 'AGRADO'],
            ['cod_dep' => '41', 'codigo' => '41016', 'nombre' => 'AIPE'],
            ['cod_dep' => '41', 'codigo' => '41020', 'nombre' => 'ALGECIRAS'],
            ['cod_dep' => '41', 'codigo' => '41026', 'nombre' => 'ALTAMIRA'],
            ['cod_dep' => '41', 'codigo' => '41078', 'nombre' => 'BARAYA'],
            ['cod_dep' => '41', 'codigo' => '41132', 'nombre' => 'CAMPOALEGRE'],
            ['cod_dep' => '41', 'codigo' => '41206', 'nombre' => 'COLOMBIA'],
            ['cod_dep' => '41', 'codigo' => '41244', 'nombre' => 'ELÍAS'],
            ['cod_dep' => '41', 'codigo' => '41298', 'nombre' => 'GARZÓN'],
            ['cod_dep' => '41', 'codigo' => '41306', 'nombre' => 'GIGANTE'],
            ['cod_dep' => '41', 'codigo' => '41319', 'nombre' => 'GUADALUPE'],
            ['cod_dep' => '41', 'codigo' => '41349', 'nombre' => 'HOBO'],
            ['cod_dep' => '41', 'codigo' => '41357', 'nombre' => 'ÍQUIRA'],
            ['cod_dep' => '41', 'codigo' => '41359', 'nombre' => 'ISNOS'],
            ['cod_dep' => '41', 'codigo' => '41378', 'nombre' => 'LA ARGENTINA (LA PLATA VIEJA)'],
            ['cod_dep' => '41', 'codigo' => '41396', 'nombre' => 'LA PLATA'],
            ['cod_dep' => '41', 'codigo' => '41483', 'nombre' => 'NÁTAGA'],
            ['cod_dep' => '41', 'codigo' => '41503', 'nombre' => 'OPORAPA'],
            ['cod_dep' => '41', 'codigo' => '41518', 'nombre' => 'PAICOL'],
            ['cod_dep' => '41', 'codigo' => '41524', 'nombre' => 'PALERMO'],
            ['cod_dep' => '41', 'codigo' => '41530', 'nombre' => 'PALESTINA'],
            ['cod_dep' => '41', 'codigo' => '41548', 'nombre' => 'PITAL'],
            ['cod_dep' => '41', 'codigo' => '41551', 'nombre' => 'PITALITO'],
            ['cod_dep' => '41', 'codigo' => '41615', 'nombre' => 'RIVERA'],
            ['cod_dep' => '41', 'codigo' => '41660', 'nombre' => 'SALADOBLANCO'],
            ['cod_dep' => '41', 'codigo' => '41668', 'nombre' => 'SAN AGUSTÍN'],
            ['cod_dep' => '41', 'codigo' => '41676', 'nombre' => 'SANTA MARÍA'],
            ['cod_dep' => '41', 'codigo' => '41770', 'nombre' => 'SUAZA'],
            ['cod_dep' => '41', 'codigo' => '41791', 'nombre' => 'TARQUI'],
            ['cod_dep' => '41', 'codigo' => '41797', 'nombre' => 'TESALIA (CARNICERÍAS)'],
            ['cod_dep' => '41', 'codigo' => '41799', 'nombre' => 'TELLO'],
            ['cod_dep' => '41', 'codigo' => '41801', 'nombre' => 'TERUEL'],
            ['cod_dep' => '41', 'codigo' => '41807', 'nombre' => 'TIMANÁ'],
            ['cod_dep' => '41', 'codigo' => '41872', 'nombre' => 'VILLAVIEJA'],
            ['cod_dep' => '41', 'codigo' => '41885', 'nombre' => 'YAGUARÁ'],

            // La Guajira (44)
            ['cod_dep' => '44', 'codigo' => '44001', 'nombre' => 'RIOHACHA'],
            ['cod_dep' => '44', 'codigo' => '44035', 'nombre' => 'ALBANIA'],
            ['cod_dep' => '44', 'codigo' => '44078', 'nombre' => 'BARRANCAS'],
            ['cod_dep' => '44', 'codigo' => '44090', 'nombre' => 'DIBULLA'],
            ['cod_dep' => '44', 'codigo' => '44098', 'nombre' => 'DISTRACCIÓN'],
            ['cod_dep' => '44', 'codigo' => '44110', 'nombre' => 'EL MOLINO'],
            ['cod_dep' => '44', 'codigo' => '44279', 'nombre' => 'FONSECA'],
            ['cod_dep' => '44', 'codigo' => '44378', 'nombre' => 'HATONUEVO'],
            ['cod_dep' => '44', 'codigo' => '44420', 'nombre' => 'LA JAGUA DEL PILAR'],
            ['cod_dep' => '44', 'codigo' => '44430', 'nombre' => 'MAICAO'],
            ['cod_dep' => '44', 'codigo' => '44560', 'nombre' => 'MANAURE'],
            ['cod_dep' => '44', 'codigo' => '44650', 'nombre' => 'SAN JUAN DEL CESAR'],
            ['cod_dep' => '44', 'codigo' => '44847', 'nombre' => 'URIBIA'],
            ['cod_dep' => '44', 'codigo' => '44855', 'nombre' => 'URUMITA'],
            ['cod_dep' => '44', 'codigo' => '44874', 'nombre' => 'VILLANUEVA'],

            // Magdalena (47)
            ['cod_dep' => '47', 'codigo' => '47001', 'nombre' => 'SANTA MARTA'],
            ['cod_dep' => '47', 'codigo' => '47030', 'nombre' => 'ALGARROBO'],
            ['cod_dep' => '47', 'codigo' => '47053', 'nombre' => 'ARACATACA'],
            ['cod_dep' => '47', 'codigo' => '47058', 'nombre' => 'ARIGUANÍ'],
            ['cod_dep' => '47', 'codigo' => '47161', 'nombre' => 'CERRO DE SAN ANTONIO'],
            ['cod_dep' => '47', 'codigo' => '47170', 'nombre' => 'CHIBOLO'],
            ['cod_dep' => '47', 'codigo' => '47189', 'nombre' => 'CIÉNAGA'],
            ['cod_dep' => '47', 'codigo' => '47205', 'nombre' => 'CONCORDIA'],
            ['cod_dep' => '47', 'codigo' => '47245', 'nombre' => 'EL BANCO'],
            ['cod_dep' => '47', 'codigo' => '47258', 'nombre' => 'EL PIÑÓN'],
            ['cod_dep' => '47', 'codigo' => '47268', 'nombre' => 'EL RETÉN'],
            ['cod_dep' => '47', 'codigo' => '47288', 'nombre' => 'FUNDACIÓN'],
            ['cod_dep' => '47', 'codigo' => '47318', 'nombre' => 'GUAMAL'],
            ['cod_dep' => '47', 'codigo' => '47460', 'nombre' => 'NUEVA GRANADA'],
            ['cod_dep' => '47', 'codigo' => '47541', 'nombre' => 'PEDRAZA'],
            ['cod_dep' => '47', 'codigo' => '47545', 'nombre' => 'PIJIÑO DEL CARMEN'],
            ['cod_dep' => '47', 'codigo' => '47551', 'nombre' => 'PIVIJAY'],
            ['cod_dep' => '47', 'codigo' => '47555', 'nombre' => 'PLATO'],
            ['cod_dep' => '47', 'codigo' => '47570', 'nombre' => 'PUEBLOVIEJO'],
            ['cod_dep' => '47', 'codigo' => '47605', 'nombre' => 'REMOLINO'],
            ['cod_dep' => '47', 'codigo' => '47660', 'nombre' => 'SABANAS DE SAN ÁNGEL'],
            ['cod_dep' => '47', 'codigo' => '47675', 'nombre' => 'SALAMINA'],
            ['cod_dep' => '47', 'codigo' => '47692', 'nombre' => 'SAN SEBASTIÁN DE BUENAVISTA'],
            ['cod_dep' => '47', 'codigo' => '47703', 'nombre' => 'SAN ZENÓN'],
            ['cod_dep' => '47', 'codigo' => '47707', 'nombre' => 'SANTA ANA'],
            ['cod_dep' => '47', 'codigo' => '47720', 'nombre' => 'SANTA BÁRBARA DE PINTO'],
            ['cod_dep' => '47', 'codigo' => '47745', 'nombre' => 'SITIONUEVO'],
            ['cod_dep' => '47', 'codigo' => '47798', 'nombre' => 'TENERIFE'],
            ['cod_dep' => '47', 'codigo' => '47960', 'nombre' => 'ZAPAYÁN'],
            ['cod_dep' => '47', 'codigo' => '47980', 'nombre' => 'ZONA BANANERA'],

            // Meta (50)
            ['cod_dep' => '50', 'codigo' => '50001', 'nombre' => 'VILLAVICENCIO'],
            ['cod_dep' => '50', 'codigo' => '50006', 'nombre' => 'ACACÍAS'],
            ['cod_dep' => '50', 'codigo' => '50110', 'nombre' => 'BARRANCA DE UPÍA'],
            ['cod_dep' => '50', 'codigo' => '50124', 'nombre' => 'CABUYARO'],
            ['cod_dep' => '50', 'codigo' => '50150', 'nombre' => 'CASTILLA LA NUEVA'],
            ['cod_dep' => '50', 'codigo' => '50223', 'nombre' => 'CUBARRAL'],
            ['cod_dep' => '50', 'codigo' => '50226', 'nombre' => 'CUMARAL'],
            ['cod_dep' => '50', 'codigo' => '50245', 'nombre' => 'EL CALVARIO'],
            ['cod_dep' => '50', 'codigo' => '50251', 'nombre' => 'EL CASTILLO'],
            ['cod_dep' => '50', 'codigo' => '50270', 'nombre' => 'EL DORADO'],
            ['cod_dep' => '50', 'codigo' => '50287', 'nombre' => 'FUENTEDEORO'],
            ['cod_dep' => '50', 'codigo' => '50313', 'nombre' => 'GRANADA'],
            ['cod_dep' => '50', 'codigo' => '50318', 'nombre' => 'GUAMAL'],
            ['cod_dep' => '50', 'codigo' => '50325', 'nombre' => 'MAPIRIPÁN'],
            ['cod_dep' => '50', 'codigo' => '50330', 'nombre' => 'MESETAS'],
            ['cod_dep' => '50', 'codigo' => '50350', 'nombre' => 'LA MACARENA'],
            ['cod_dep' => '50', 'codigo' => '50370', 'nombre' => 'URIBE'],
            ['cod_dep' => '50', 'codigo' => '50400', 'nombre' => 'LEJANÍAS'],
            ['cod_dep' => '50', 'codigo' => '50450', 'nombre' => 'PUERTO CONCORDIA'],
            ['cod_dep' => '50', 'codigo' => '50568', 'nombre' => 'PUERTO GAITÁN'],
            ['cod_dep' => '50', 'codigo' => '50573', 'nombre' => 'PUERTO LÓPEZ'],
            ['cod_dep' => '50', 'codigo' => '50577', 'nombre' => 'PUERTO LLERAS'],
            ['cod_dep' => '50', 'codigo' => '50590', 'nombre' => 'PUERTO RICO'],
            ['cod_dep' => '50', 'codigo' => '50606', 'nombre' => 'RESTREPO'],
            ['cod_dep' => '50', 'codigo' => '50680', 'nombre' => 'SAN CARLOS DE GUAROA'],
            ['cod_dep' => '50', 'codigo' => '50683', 'nombre' => 'SAN JUAN DE ARAMA'],
            ['cod_dep' => '50', 'codigo' => '50686', 'nombre' => 'SAN JUANITO'],
            ['cod_dep' => '50', 'codigo' => '50689', 'nombre' => 'SAN MARTÍN DE LOS LLANOS'],
            ['cod_dep' => '50', 'codigo' => '50711', 'nombre' => 'VISTAHERMOSA'],
        ];

        // Nariño (52), Norte de Santander (54), Putumayo (86), Quindío (63), Risaralda (66), Santander (68)
        $batch5 = [
            // Nariño (52)
            ['cod_dep' => '52', 'codigo' => '52001', 'nombre' => 'PASTO'],
            ['cod_dep' => '52', 'codigo' => '52019', 'nombre' => 'ALBÁN (SAN JOSÉ)'],
            ['cod_dep' => '52', 'codigo' => '52022', 'nombre' => 'ALDANA'],
            ['cod_dep' => '52', 'codigo' => '52036', 'nombre' => 'ANCUYÁ'],
            ['cod_dep' => '52', 'codigo' => '52051', 'nombre' => 'ARBOLEDA'],
            ['cod_dep' => '52', 'codigo' => '52079', 'nombre' => 'BARBACOAS'],
            ['cod_dep' => '52', 'codigo' => '52083', 'nombre' => 'BELÉN'],
            ['cod_dep' => '52', 'codigo' => '52110', 'nombre' => 'BUESACO'],
            ['cod_dep' => '52', 'codigo' => '52203', 'nombre' => 'COLÓN (GÉNOVA)'],
            ['cod_dep' => '52', 'codigo' => '52207', 'nombre' => 'CONSACÁ'],
            ['cod_dep' => '52', 'codigo' => '52210', 'nombre' => 'CONTADERO'],
            ['cod_dep' => '52', 'codigo' => '52215', 'nombre' => 'CÓRDOBA'],
            ['cod_dep' => '52', 'codigo' => '52224', 'nombre' => 'CUASPÚD'],
            ['cod_dep' => '52', 'codigo' => '52227', 'nombre' => 'CUMBAL'],
            ['cod_dep' => '52', 'codigo' => '52233', 'nombre' => 'CUMBITARA'],
            ['cod_dep' => '52', 'codigo' => '52240', 'nombre' => 'CHACHAGÜÍ'],
            ['cod_dep' => '52', 'codigo' => '52250', 'nombre' => 'EL CHARCO'],
            ['cod_dep' => '52', 'codigo' => '52254', 'nombre' => 'EL PEÑOL'],
            ['cod_dep' => '52', 'codigo' => '52256', 'nombre' => 'EL ROSARIO'],
            ['cod_dep' => '52', 'codigo' => '52258', 'nombre' => 'EL TABLÓN DE GÓMEZ'],
            ['cod_dep' => '52', 'codigo' => '52260', 'nombre' => 'EL TAMBO'],
            ['cod_dep' => '52', 'codigo' => '52287', 'nombre' => 'FUNES'],
            ['cod_dep' => '52', 'codigo' => '52317', 'nombre' => 'GUACHUCAL'],
            ['cod_dep' => '52', 'codigo' => '52320', 'nombre' => 'GUAITARILLA'],
            ['cod_dep' => '52', 'codigo' => '52323', 'nombre' => 'GUALMATÁN'],
            ['cod_dep' => '52', 'codigo' => '52352', 'nombre' => 'ILES'],
            ['cod_dep' => '52', 'codigo' => '52354', 'nombre' => 'IMUÉS'],
            ['cod_dep' => '52', 'codigo' => '52356', 'nombre' => 'IPIALES'],
            ['cod_dep' => '52', 'codigo' => '52378', 'nombre' => 'LA CRUZ'],
            ['cod_dep' => '52', 'codigo' => '52381', 'nombre' => 'LA FLORIDA'],
            ['cod_dep' => '52', 'codigo' => '52385', 'nombre' => 'LA LLANADA'],
            ['cod_dep' => '52', 'codigo' => '52390', 'nombre' => 'LA TOLA'],
            ['cod_dep' => '52', 'codigo' => '52399', 'nombre' => 'LA UNIÓN'],
            ['cod_dep' => '52', 'codigo' => '52405', 'nombre' => 'LEIVA'],
            ['cod_dep' => '52', 'codigo' => '52411', 'nombre' => 'LINARES'],
            ['cod_dep' => '52', 'codigo' => '52418', 'nombre' => 'LOS ANDES (SOTOMAYOR)'],
            ['cod_dep' => '52', 'codigo' => '52427', 'nombre' => 'MAGÜÍ (PAYÁN)'],
            ['cod_dep' => '52', 'codigo' => '52435', 'nombre' => 'MALLAMA (PIEDRANCHA)'],
            ['cod_dep' => '52', 'codigo' => '52473', 'nombre' => 'MOSQUERA'],
            ['cod_dep' => '52', 'codigo' => '52480', 'nombre' => 'NARIÑO'],
            ['cod_dep' => '52', 'codigo' => '52490', 'nombre' => 'OLAYA HERRERA'],
            ['cod_dep' => '52', 'codigo' => '52506', 'nombre' => 'OSPINA'],
            ['cod_dep' => '52', 'codigo' => '52520', 'nombre' => 'FRANCISCO PIZARRO'],
            ['cod_dep' => '52', 'codigo' => '52540', 'nombre' => 'POLICARPA'],
            ['cod_dep' => '52', 'codigo' => '52560', 'nombre' => 'POTOSÍ'],
            ['cod_dep' => '52', 'codigo' => '52565', 'nombre' => 'PROVIDENCIA'],
            ['cod_dep' => '52', 'codigo' => '52573', 'nombre' => 'PUERRES'],
            ['cod_dep' => '52', 'codigo' => '52585', 'nombre' => 'PUPIALES'],
            ['cod_dep' => '52', 'codigo' => '52612', 'nombre' => 'RICAURTE'],
            ['cod_dep' => '52', 'codigo' => '52621', 'nombre' => 'ROBERTO PAYÁN (SAN JOSÉ)'],
            ['cod_dep' => '52', 'codigo' => '52678', 'nombre' => 'SAMANIEGO'],
            ['cod_dep' => '52', 'codigo' => '52683', 'nombre' => 'SANDONÁ'],
            ['cod_dep' => '52', 'codigo' => '52685', 'nombre' => 'SAN BERNARDO'],
            ['cod_dep' => '52', 'codigo' => '52687', 'nombre' => 'SAN LORENZO'],
            ['cod_dep' => '52', 'codigo' => '52693', 'nombre' => 'SAN PABLO'],
            ['cod_dep' => '52', 'codigo' => '52694', 'nombre' => 'SAN PEDRO DE CARTAGO'],
            ['cod_dep' => '52', 'codigo' => '52696', 'nombre' => 'SANTA BÁRBARA'],
            ['cod_dep' => '52', 'codigo' => '52699', 'nombre' => 'SANTACRUZ'],
            ['cod_dep' => '52', 'codigo' => '52720', 'nombre' => 'SAPUYES'],
            ['cod_dep' => '52', 'codigo' => '52786', 'nombre' => 'TAMINANGO'],
            ['cod_dep' => '52', 'codigo' => '52788', 'nombre' => 'TANGUA'],
            ['cod_dep' => '52', 'codigo' => '52835', 'nombre' => 'SAN ANDRÉS DE TUMACO'],
            ['cod_dep' => '52', 'codigo' => '52838', 'nombre' => 'TÚQUERRES'],
            ['cod_dep' => '52', 'codigo' => '52885', 'nombre' => 'YACUANQUER'],

            // Norte de Santander (54)
            ['cod_dep' => '54', 'codigo' => '54001', 'nombre' => 'CÚCUTA'],
            ['cod_dep' => '54', 'codigo' => '54003', 'nombre' => 'ÁBREGO'],
            ['cod_dep' => '54', 'codigo' => '54051', 'nombre' => 'ARBOLEDAS'],
            ['cod_dep' => '54', 'codigo' => '54099', 'nombre' => 'BOCHALEMA'],
            ['cod_dep' => '54', 'codigo' => '54109', 'nombre' => 'BUCARASICA'],
            ['cod_dep' => '54', 'codigo' => '54125', 'nombre' => 'CÁCOTA DE VELASCO'],
            ['cod_dep' => '54', 'codigo' => '54128', 'nombre' => 'CÁCHIRA'],
            ['cod_dep' => '54', 'codigo' => '54172', 'nombre' => 'CHINÁCOTA'],
            ['cod_dep' => '54', 'codigo' => '54174', 'nombre' => 'CHITAGÁ'],
            ['cod_dep' => '54', 'codigo' => '54206', 'nombre' => 'CONVENCIÓN'],
            ['cod_dep' => '54', 'codigo' => '54223', 'nombre' => 'CUCUTILLA'],
            ['cod_dep' => '54', 'codigo' => '54239', 'nombre' => 'DURANIA'],
            ['cod_dep' => '54', 'codigo' => '54245', 'nombre' => 'EL CARMEN'],
            ['cod_dep' => '54', 'codigo' => '54250', 'nombre' => 'EL TARRA'],
            ['cod_dep' => '54', 'codigo' => '54261', 'nombre' => 'EL ZULIA'],
            ['cod_dep' => '54', 'codigo' => '54313', 'nombre' => 'GRAMALOTE'],
            ['cod_dep' => '54', 'codigo' => '54344', 'nombre' => 'HACARÍ'],
            ['cod_dep' => '54', 'codigo' => '54347', 'nombre' => 'HERRÁN'],
            ['cod_dep' => '54', 'codigo' => '54377', 'nombre' => 'LABATECA'],
            ['cod_dep' => '54', 'codigo' => '54385', 'nombre' => 'LA ESPERANZA'],
            ['cod_dep' => '54', 'codigo' => '54398', 'nombre' => 'LA PLAYA DE BELÉN'],
            ['cod_dep' => '54', 'codigo' => '54405', 'nombre' => 'LOS PATIOS'],
            ['cod_dep' => '54', 'codigo' => '54418', 'nombre' => 'LOURDES'],
            ['cod_dep' => '54', 'codigo' => '54480', 'nombre' => 'MUTISCUA'],
            ['cod_dep' => '54', 'codigo' => '54498', 'nombre' => 'OCAÑA'],
            ['cod_dep' => '54', 'codigo' => '54518', 'nombre' => 'PAMPLONA'],
            ['cod_dep' => '54', 'codigo' => '54520', 'nombre' => 'PAMPLONITA'],
            ['cod_dep' => '54', 'codigo' => '54553', 'nombre' => 'PUERTO SANTANDER'],
            ['cod_dep' => '54', 'codigo' => '54599', 'nombre' => 'RAGONVALIA'],
            ['cod_dep' => '54', 'codigo' => '54660', 'nombre' => 'SALAZAR DE LAS PALMAS'],
            ['cod_dep' => '54', 'codigo' => '54670', 'nombre' => 'SAN CALIXTO'],
            ['cod_dep' => '54', 'codigo' => '54673', 'nombre' => 'SAN CAYETANO'],
            ['cod_dep' => '54', 'codigo' => '54680', 'nombre' => 'SANTIAGO'],
            ['cod_dep' => '54', 'codigo' => '54720', 'nombre' => 'SARDINATA'],
            ['cod_dep' => '54', 'codigo' => '54743', 'nombre' => 'SANTO DOMINGO DE SILOS'],
            ['cod_dep' => '54', 'codigo' => '54800', 'nombre' => 'TEORAMA'],
            ['cod_dep' => '54', 'codigo' => '54810', 'nombre' => 'TIBÚ'],
            ['cod_dep' => '54', 'codigo' => '54820', 'nombre' => 'TOLEDO'],
            ['cod_dep' => '54', 'codigo' => '54871', 'nombre' => 'VILLA CARO'],
            ['cod_dep' => '54', 'codigo' => '54874', 'nombre' => 'VILLA DEL ROSARIO'],

            // Putumayo (86)
            ['cod_dep' => '86', 'codigo' => '86001', 'nombre' => 'MOCOA'],
            ['cod_dep' => '86', 'codigo' => '86219', 'nombre' => 'COLÓN'],
            ['cod_dep' => '86', 'codigo' => '86320', 'nombre' => 'ORITO'],
            ['cod_dep' => '86', 'codigo' => '86568', 'nombre' => 'PUERTO ASÍS'],
            ['cod_dep' => '86', 'codigo' => '86569', 'nombre' => 'PUERTO CAICEDO'],
            ['cod_dep' => '86', 'codigo' => '86571', 'nombre' => 'PUERTO GUZMÁN'],
            ['cod_dep' => '86', 'codigo' => '86573', 'nombre' => 'PUERTO LEGUÍZAMO'],
            ['cod_dep' => '86', 'codigo' => '86749', 'nombre' => 'SIBUNDOY'],
            ['cod_dep' => '86', 'codigo' => '86755', 'nombre' => 'SAN FRANCISCO'],
            ['cod_dep' => '86', 'codigo' => '86757', 'nombre' => 'SAN MIGUEL'],
            ['cod_dep' => '86', 'codigo' => '86760', 'nombre' => 'SANTIAGO'],
            ['cod_dep' => '86', 'codigo' => '86865', 'nombre' => 'VALLE DEL GUAMUEZ'],
            ['cod_dep' => '86', 'codigo' => '86885', 'nombre' => 'VILLAGARZÓN'],

            // Quindío (63)
            ['cod_dep' => '63', 'codigo' => '63001', 'nombre' => 'ARMENIA'],
            ['cod_dep' => '63', 'codigo' => '63111', 'nombre' => 'BUENAVISTA'],
            ['cod_dep' => '63', 'codigo' => '63130', 'nombre' => 'CALARCÁ'],
            ['cod_dep' => '63', 'codigo' => '63190', 'nombre' => 'CIRCASIA'],
            ['cod_dep' => '63', 'codigo' => '63212', 'nombre' => 'CÓRDOBA'],
            ['cod_dep' => '63', 'codigo' => '63272', 'nombre' => 'FILANDIA'],
            ['cod_dep' => '63', 'codigo' => '63302', 'nombre' => 'GÉNOVA'],
            ['cod_dep' => '63', 'codigo' => '63401', 'nombre' => 'LA TEBAIDA'],
            ['cod_dep' => '63', 'codigo' => '63470', 'nombre' => 'MONTENEGRO'],
            ['cod_dep' => '63', 'codigo' => '63548', 'nombre' => 'PIJAO'],
            ['cod_dep' => '63', 'codigo' => '63594', 'nombre' => 'QUIMBAYA'],
            ['cod_dep' => '63', 'codigo' => '63690', 'nombre' => 'SALENTO'],

            // Risaralda (66)
            ['cod_dep' => '66', 'codigo' => '66001', 'nombre' => 'PEREIRA'],
            ['cod_dep' => '66', 'codigo' => '66045', 'nombre' => 'APÍA'],
            ['cod_dep' => '66', 'codigo' => '66075', 'nombre' => 'BALBOA'],
            ['cod_dep' => '66', 'codigo' => '66088', 'nombre' => 'BELÉN DE UMBRÍA'],
            ['cod_dep' => '66', 'codigo' => '66170', 'nombre' => 'DOSQUEBRADAS'],
            ['cod_dep' => '66', 'codigo' => '66318', 'nombre' => 'GUÁTICA'],
            ['cod_dep' => '66', 'codigo' => '66383', 'nombre' => 'LA CELIA'],
            ['cod_dep' => '66', 'codigo' => '66400', 'nombre' => 'LA VIRGINIA'],
            ['cod_dep' => '66', 'codigo' => '66440', 'nombre' => 'MARSELLA'],
            ['cod_dep' => '66', 'codigo' => '66456', 'nombre' => 'MISTRATÓ'],
            ['cod_dep' => '66', 'codigo' => '66572', 'nombre' => 'PUEBLO RICO'],
            ['cod_dep' => '66', 'codigo' => '66594', 'nombre' => 'QUINCHÍA'],
            ['cod_dep' => '66', 'codigo' => '66682', 'nombre' => 'SANTA ROSA DE CABAL'],
            ['cod_dep' => '66', 'codigo' => '66687', 'nombre' => 'SANTUARIO'],

            // Santander (68)
            ['cod_dep' => '68', 'codigo' => '68001', 'nombre' => 'BUCARAMANGA'],
            ['cod_dep' => '68', 'codigo' => '68013', 'nombre' => 'AGUADA'],
            ['cod_dep' => '68', 'codigo' => '68020', 'nombre' => 'ALBANIA'],
            ['cod_dep' => '68', 'codigo' => '68051', 'nombre' => 'ARATOCA'],
            ['cod_dep' => '68', 'codigo' => '68077', 'nombre' => 'BARBOSA'],
            ['cod_dep' => '68', 'codigo' => '68079', 'nombre' => 'BARICHARA'],
            ['cod_dep' => '68', 'codigo' => '68081', 'nombre' => 'BARRANCABERMEJA'],
            ['cod_dep' => '68', 'codigo' => '68092', 'nombre' => 'BETULIA'],
            ['cod_dep' => '68', 'codigo' => '68101', 'nombre' => 'BOLÍVAR'],
            ['cod_dep' => '68', 'codigo' => '68121', 'nombre' => 'CABRERA'],
            ['cod_dep' => '68', 'codigo' => '68132', 'nombre' => 'CALIFORNIA'],
            ['cod_dep' => '68', 'codigo' => '68147', 'nombre' => 'CAPITANEJO'],
            ['cod_dep' => '68', 'codigo' => '68152', 'nombre' => 'CARCASÍ'],
            ['cod_dep' => '68', 'codigo' => '68160', 'nombre' => 'CEPITÁ'],
            ['cod_dep' => '68', 'codigo' => '68162', 'nombre' => 'CERRITO'],
            ['cod_dep' => '68', 'codigo' => '68167', 'nombre' => 'CHARALÁ'],
            ['cod_dep' => '68', 'codigo' => '68169', 'nombre' => 'CHARTA'],
            ['cod_dep' => '68', 'codigo' => '68176', 'nombre' => 'CHIMA'],
            ['cod_dep' => '68', 'codigo' => '68179', 'nombre' => 'CHIPATÁ'],
            ['cod_dep' => '68', 'codigo' => '68190', 'nombre' => 'CIMITARRA'],
            ['cod_dep' => '68', 'codigo' => '68207', 'nombre' => 'CONCEPCIÓN'],
            ['cod_dep' => '68', 'codigo' => '68209', 'nombre' => 'CONFINES'],
            ['cod_dep' => '68', 'codigo' => '68211', 'nombre' => 'CONTRATACIÓN'],
            ['cod_dep' => '68', 'codigo' => '68217', 'nombre' => 'COROMORO'],
            ['cod_dep' => '68', 'codigo' => '68229', 'nombre' => 'CURITÍ'],
            ['cod_dep' => '68', 'codigo' => '68235', 'nombre' => 'EL CARMEN DE CHUCURÍ'],
            ['cod_dep' => '68', 'codigo' => '68245', 'nombre' => 'EL GUACAMAYO'],
            ['cod_dep' => '68', 'codigo' => '68250', 'nombre' => 'EL PEÑÓN'],
            ['cod_dep' => '68', 'codigo' => '68255', 'nombre' => 'EL PLAYÓN'],
            ['cod_dep' => '68', 'codigo' => '68264', 'nombre' => 'ENCINO'],
            ['cod_dep' => '68', 'codigo' => '68266', 'nombre' => 'ENCISO'],
            ['cod_dep' => '68', 'codigo' => '68271', 'nombre' => 'FLORIÁN'],
            ['cod_dep' => '68', 'codigo' => '68276', 'nombre' => 'FLORIDABLANCA'],
            ['cod_dep' => '68', 'codigo' => '68296', 'nombre' => 'GALÁN'],
            ['cod_dep' => '68', 'codigo' => '68298', 'nombre' => 'GÁMBITA'],
            ['cod_dep' => '68', 'codigo' => '68307', 'nombre' => 'GIRÓN'],
            ['cod_dep' => '68', 'codigo' => '68318', 'nombre' => 'GUACA'],
            ['cod_dep' => '68', 'codigo' => '68320', 'nombre' => 'GUADALUPE'],
            ['cod_dep' => '68', 'codigo' => '68322', 'nombre' => 'GUAPOTÁ'],
            ['cod_dep' => '68', 'codigo' => '68324', 'nombre' => 'GUAVATÁ'],
            ['cod_dep' => '68', 'codigo' => '68327', 'nombre' => 'GÜEPSA'],
            ['cod_dep' => '68', 'codigo' => '68344', 'nombre' => 'HATO'],
            ['cod_dep' => '68', 'codigo' => '68368', 'nombre' => 'JESÚS MARÍA'],
            ['cod_dep' => '68', 'codigo' => '68370', 'nombre' => 'JORDÁN'],
            ['cod_dep' => '68', 'codigo' => '68377', 'nombre' => 'LA BELLEZA'],
            ['cod_dep' => '68', 'codigo' => '68385', 'nombre' => 'LANDÁZURI'],
            ['cod_dep' => '68', 'codigo' => '68397', 'nombre' => 'LA PAZ'],
            ['cod_dep' => '68', 'codigo' => '68406', 'nombre' => 'LEBRIJA'],
            ['cod_dep' => '68', 'codigo' => '68418', 'nombre' => 'LOS SANTOS'],
            ['cod_dep' => '68', 'codigo' => '68425', 'nombre' => 'MACARAVITA'],
            ['cod_dep' => '68', 'codigo' => '68432', 'nombre' => 'MÁLAGA'],
            ['cod_dep' => '68', 'codigo' => '68444', 'nombre' => 'MATANZA'],
            ['cod_dep' => '68', 'codigo' => '68464', 'nombre' => 'MOGOTES'],
            ['cod_dep' => '68', 'codigo' => '68468', 'nombre' => 'MOLAGAVITA'],
            ['cod_dep' => '68', 'codigo' => '68498', 'nombre' => 'OCAMONTE'],
            ['cod_dep' => '68', 'codigo' => '68500', 'nombre' => 'OIBA'],
            ['cod_dep' => '68', 'codigo' => '68502', 'nombre' => 'ONZAGA'],
            ['cod_dep' => '68', 'codigo' => '68522', 'nombre' => 'PALMAR'],
            ['cod_dep' => '68', 'codigo' => '68524', 'nombre' => 'PALMAS DEL SOCORRO'],
            ['cod_dep' => '68', 'codigo' => '68533', 'nombre' => 'PÁRAMO'],
            ['cod_dep' => '68', 'codigo' => '68547', 'nombre' => 'PIEDECUESTA'],
            ['cod_dep' => '68', 'codigo' => '68549', 'nombre' => 'PINCHOTE'],
            ['cod_dep' => '68', 'codigo' => '68572', 'nombre' => 'PUENTE NACIONAL'],
            ['cod_dep' => '68', 'codigo' => '68573', 'nombre' => 'PUERTO PARRA'],
            ['cod_dep' => '68', 'codigo' => '68575', 'nombre' => 'PUERTO WILCHES'],
            ['cod_dep' => '68', 'codigo' => '68615', 'nombre' => 'RIONEGRO'],
            ['cod_dep' => '68', 'codigo' => '68655', 'nombre' => 'SABANA DE TORRES'],
            ['cod_dep' => '68', 'codigo' => '68669', 'nombre' => 'SAN ANDRÉS'],
            ['cod_dep' => '68', 'codigo' => '68673', 'nombre' => 'SAN BENITO'],
            ['cod_dep' => '68', 'codigo' => '68679', 'nombre' => 'SAN GIL'],
            ['cod_dep' => '68', 'codigo' => '68682', 'nombre' => 'SAN JOAQUÍN'],
            ['cod_dep' => '68', 'codigo' => '68684', 'nombre' => 'SAN JOSÉ DE MIRANDA'],
            ['cod_dep' => '68', 'codigo' => '68686', 'nombre' => 'SAN MIGUEL'],
            ['cod_dep' => '68', 'codigo' => '68689', 'nombre' => 'SAN VICENTE DE CHUCURÍ'],
            ['cod_dep' => '68', 'codigo' => '68705', 'nombre' => 'SANTA BÁRBARA'],
            ['cod_dep' => '68', 'codigo' => '68720', 'nombre' => 'SANTA HELENA DEL OPÓN'],
            ['cod_dep' => '68', 'codigo' => '68745', 'nombre' => 'SIMACOTA'],
            ['cod_dep' => '68', 'codigo' => '68755', 'nombre' => 'SOCORRO'],
            ['cod_dep' => '68', 'codigo' => '68770', 'nombre' => 'SUAITA'],
            ['cod_dep' => '68', 'codigo' => '68773', 'nombre' => 'SUCRE'],
            ['cod_dep' => '68', 'codigo' => '68780', 'nombre' => 'SURATÁ'],
            ['cod_dep' => '68', 'codigo' => '68820', 'nombre' => 'TONA'],
            ['cod_dep' => '68', 'codigo' => '68855', 'nombre' => 'VALLE DE SAN JOSÉ'],
            ['cod_dep' => '68', 'codigo' => '68861', 'nombre' => 'VÉLEZ'],
            ['cod_dep' => '68', 'codigo' => '68867', 'nombre' => 'VETAS'],
            ['cod_dep' => '68', 'codigo' => '68872', 'nombre' => 'VILLANUEVA'],
            ['cod_dep' => '68', 'codigo' => '68895', 'nombre' => 'ZAPATOCA'],
        ];

        // Sucre (70), Tolima (73), Valle del Cauca (76), Vaupés (97), Vichada (99)
        $batch6 = [
            // Sucre (70)
            ['cod_dep' => '70', 'codigo' => '70001', 'nombre' => 'SINCELEJO'],
            ['cod_dep' => '70', 'codigo' => '70110', 'nombre' => 'BUENAVISTA'],
            ['cod_dep' => '70', 'codigo' => '70124', 'nombre' => 'CAIMITO'],
            ['cod_dep' => '70', 'codigo' => '70204', 'nombre' => 'COLOSÓ'],
            ['cod_dep' => '70', 'codigo' => '70215', 'nombre' => 'COROZAL'],
            ['cod_dep' => '70', 'codigo' => '70221', 'nombre' => 'COVEÑAS'],
            ['cod_dep' => '70', 'codigo' => '70230', 'nombre' => 'CHALÁN'],
            ['cod_dep' => '70', 'codigo' => '70233', 'nombre' => 'EL ROBLE'],
            ['cod_dep' => '70', 'codigo' => '70235', 'nombre' => 'GALERAS'],
            ['cod_dep' => '70', 'codigo' => '70265', 'nombre' => 'GUARANDA'],
            ['cod_dep' => '70', 'codigo' => '70400', 'nombre' => 'LA UNIÓN'],
            ['cod_dep' => '70', 'codigo' => '70418', 'nombre' => 'LOS PALMITOS'],
            ['cod_dep' => '70', 'codigo' => '70429', 'nombre' => 'MAJAGUAL'],
            ['cod_dep' => '70', 'codigo' => '70473', 'nombre' => 'MORROA'],
            ['cod_dep' => '70', 'codigo' => '70508', 'nombre' => 'OVEJAS'],
            ['cod_dep' => '70', 'codigo' => '70523', 'nombre' => 'PALMITO'],
            ['cod_dep' => '70', 'codigo' => '70670', 'nombre' => 'SAMPUÉS'],
            ['cod_dep' => '70', 'codigo' => '70678', 'nombre' => 'SAN BENITO ABAD'],
            ['cod_dep' => '70', 'codigo' => '70702', 'nombre' => 'SAN JUAN DE BETULIA'],
            ['cod_dep' => '70', 'codigo' => '70708', 'nombre' => 'SAN MARCOS'],
            ['cod_dep' => '70', 'codigo' => '70713', 'nombre' => 'SAN ONOFRE'],
            ['cod_dep' => '70', 'codigo' => '70717', 'nombre' => 'SAN PEDRO'],
            ['cod_dep' => '70', 'codigo' => '70742', 'nombre' => 'SAN LUIS DE SINCÉ'],
            ['cod_dep' => '70', 'codigo' => '70771', 'nombre' => 'SUCRE'],
            ['cod_dep' => '70', 'codigo' => '70820', 'nombre' => 'SANTIAGO DE TOLÚ'],
            ['cod_dep' => '70', 'codigo' => '70823', 'nombre' => 'TOLÚ VIEJO'],

            // Tolima (73)
            ['cod_dep' => '73', 'codigo' => '73001', 'nombre' => 'IBAGUÉ'],
            ['cod_dep' => '73', 'codigo' => '73024', 'nombre' => 'ALPUJARRA'],
            ['cod_dep' => '73', 'codigo' => '73026', 'nombre' => 'ALVARADO'],
            ['cod_dep' => '73', 'codigo' => '73030', 'nombre' => 'AMBALEMA'],
            ['cod_dep' => '73', 'codigo' => '73043', 'nombre' => 'ANZOÁTEGUI'],
            ['cod_dep' => '73', 'codigo' => '73055', 'nombre' => 'ARMERO (GUAYABAL)'],
            ['cod_dep' => '73', 'codigo' => '73067', 'nombre' => 'ATACO'],
            ['cod_dep' => '73', 'codigo' => '73124', 'nombre' => 'CAJAMARCA'],
            ['cod_dep' => '73', 'codigo' => '73148', 'nombre' => 'CARMEN DE APICALÁ'],
            ['cod_dep' => '73', 'codigo' => '73152', 'nombre' => 'CASABIANCA'],
            ['cod_dep' => '73', 'codigo' => '73168', 'nombre' => 'CHAPARRAL'],
            ['cod_dep' => '73', 'codigo' => '73200', 'nombre' => 'COELLO'],
            ['cod_dep' => '73', 'codigo' => '73217', 'nombre' => 'COYAIMA'],
            ['cod_dep' => '73', 'codigo' => '73226', 'nombre' => 'CUNDAY'],
            ['cod_dep' => '73', 'codigo' => '73236', 'nombre' => 'DOLORES'],
            ['cod_dep' => '73', 'codigo' => '73268', 'nombre' => 'ESPINAL'],
            ['cod_dep' => '73', 'codigo' => '73270', 'nombre' => 'FALAN'],
            ['cod_dep' => '73', 'codigo' => '73275', 'nombre' => 'FLANDES'],
            ['cod_dep' => '73', 'codigo' => '73283', 'nombre' => 'FRESNO'],
            ['cod_dep' => '73', 'codigo' => '73319', 'nombre' => 'GUAMO'],
            ['cod_dep' => '73', 'codigo' => '73347', 'nombre' => 'HERVEO'],
            ['cod_dep' => '73', 'codigo' => '73349', 'nombre' => 'HONDA'],
            ['cod_dep' => '73', 'codigo' => '73352', 'nombre' => 'ICONONZO'],
            ['cod_dep' => '73', 'codigo' => '73408', 'nombre' => 'LÉRIDA'],
            ['cod_dep' => '73', 'codigo' => '73411', 'nombre' => 'LÍBANO'],
            ['cod_dep' => '73', 'codigo' => '73443', 'nombre' => 'SAN SEBASTIÁN DE MARIQUITA'],
            ['cod_dep' => '73', 'codigo' => '73449', 'nombre' => 'MELGAR'],
            ['cod_dep' => '73', 'codigo' => '73461', 'nombre' => 'MURILLO'],
            ['cod_dep' => '73', 'codigo' => '73483', 'nombre' => 'NATAGAIMA'],
            ['cod_dep' => '73', 'codigo' => '73504', 'nombre' => 'ORTEGA'],
            ['cod_dep' => '73', 'codigo' => '73520', 'nombre' => 'PALOCABILDO'],
            ['cod_dep' => '73', 'codigo' => '73547', 'nombre' => 'PIEDRAS'],
            ['cod_dep' => '73', 'codigo' => '73555', 'nombre' => 'PLANADAS'],
            ['cod_dep' => '73', 'codigo' => '73563', 'nombre' => 'PRADO'],
            ['cod_dep' => '73', 'codigo' => '73585', 'nombre' => 'PURIFICACIÓN'],
            ['cod_dep' => '73', 'codigo' => '73616', 'nombre' => 'RIOBLANCO'],
            ['cod_dep' => '73', 'codigo' => '73622', 'nombre' => 'RONCESVALLES'],
            ['cod_dep' => '73', 'codigo' => '73624', 'nombre' => 'ROVIRA'],
            ['cod_dep' => '73', 'codigo' => '73671', 'nombre' => 'SALDAÑA'],
            ['cod_dep' => '73', 'codigo' => '73675', 'nombre' => 'SAN ANTONIO'],
            ['cod_dep' => '73', 'codigo' => '73678', 'nombre' => 'SAN LUIS'],
            ['cod_dep' => '73', 'codigo' => '73686', 'nombre' => 'SANTA ISABEL'],
            ['cod_dep' => '73', 'codigo' => '73770', 'nombre' => 'SUÁREZ'],
            ['cod_dep' => '73', 'codigo' => '73854', 'nombre' => 'VALLE DE SAN JUAN'],
            ['cod_dep' => '73', 'codigo' => '73861', 'nombre' => 'VENADILLO'],
            ['cod_dep' => '73', 'codigo' => '73870', 'nombre' => 'VILLAHERMOSA'],
            ['cod_dep' => '73', 'codigo' => '73873', 'nombre' => 'VILLARRICA'],

            // Valle del Cauca (76)
            ['cod_dep' => '76', 'codigo' => '76001', 'nombre' => 'CALI'],
            ['cod_dep' => '76', 'codigo' => '76020', 'nombre' => 'ALCALÁ'],
            ['cod_dep' => '76', 'codigo' => '76036', 'nombre' => 'ANDALUCÍA'],
            ['cod_dep' => '76', 'codigo' => '76041', 'nombre' => 'ANSERMANUEVO'],
            ['cod_dep' => '76', 'codigo' => '76054', 'nombre' => 'ARGELIA'],
            ['cod_dep' => '76', 'codigo' => '76100', 'nombre' => 'BOLÍVAR'],
            ['cod_dep' => '76', 'codigo' => '76109', 'nombre' => 'BUENAVENTURA'],
            ['cod_dep' => '76', 'codigo' => '76111', 'nombre' => 'GUADALAJARA DE BUGA'],
            ['cod_dep' => '76', 'codigo' => '76113', 'nombre' => 'BUGALAGRANDE'],
            ['cod_dep' => '76', 'codigo' => '76122', 'nombre' => 'CAICEDONIA'],
            ['cod_dep' => '76', 'codigo' => '76126', 'nombre' => 'CALIMA (DARIEN)'],
            ['cod_dep' => '76', 'codigo' => '76130', 'nombre' => 'CANDELARIA'],
            ['cod_dep' => '76', 'codigo' => '76147', 'nombre' => 'CARTAGO'],
            ['cod_dep' => '76', 'codigo' => '76233', 'nombre' => 'DAGUA'],
            ['cod_dep' => '76', 'codigo' => '76243', 'nombre' => 'EL ÁGUILA'],
            ['cod_dep' => '76', 'codigo' => '76246', 'nombre' => 'EL CAIRO'],
            ['cod_dep' => '76', 'codigo' => '76248', 'nombre' => 'EL CERRITO'],
            ['cod_dep' => '76', 'codigo' => '76250', 'nombre' => 'EL DOVIO'],
            ['cod_dep' => '76', 'codigo' => '76275', 'nombre' => 'FLORIDA'],
            ['cod_dep' => '76', 'codigo' => '76306', 'nombre' => 'GINEBRA'],
            ['cod_dep' => '76', 'codigo' => '76318', 'nombre' => 'GUACARÍ'],
            ['cod_dep' => '76', 'codigo' => '76364', 'nombre' => 'JAMUNDÍ'],
            ['cod_dep' => '76', 'codigo' => '76377', 'nombre' => 'LA CUMBRE'],
            ['cod_dep' => '76', 'codigo' => '76400', 'nombre' => 'LA UNIÓN'],
            ['cod_dep' => '76', 'codigo' => '76403', 'nombre' => 'LA VICTORIA'],
            ['cod_dep' => '76', 'codigo' => '76497', 'nombre' => 'OBANDO'],
            ['cod_dep' => '76', 'codigo' => '76520', 'nombre' => 'PALMIRA'],
            ['cod_dep' => '76', 'codigo' => '76563', 'nombre' => 'PRADERA'],
            ['cod_dep' => '76', 'codigo' => '76606', 'nombre' => 'RESTREPO'],
            ['cod_dep' => '76', 'codigo' => '76616', 'nombre' => 'RIOFRÍO'],
            ['cod_dep' => '76', 'codigo' => '76622', 'nombre' => 'ROLDANILLO'],
            ['cod_dep' => '76', 'codigo' => '76670', 'nombre' => 'SAN PEDRO'],
            ['cod_dep' => '76', 'codigo' => '76736', 'nombre' => 'SEVILLA'],
            ['cod_dep' => '76', 'codigo' => '76823', 'nombre' => 'TORO'],
            ['cod_dep' => '76', 'codigo' => '76828', 'nombre' => 'TRUJILLO'],
            ['cod_dep' => '76', 'codigo' => '76834', 'nombre' => 'TULUÁ'],
            ['cod_dep' => '76', 'codigo' => '76845', 'nombre' => 'ULLOA'],
            ['cod_dep' => '76', 'codigo' => '76863', 'nombre' => 'VERSALLES'],
            ['cod_dep' => '76', 'codigo' => '76869', 'nombre' => 'VIJES'],
            ['cod_dep' => '76', 'codigo' => '76890', 'nombre' => 'YOTOCO'],
            ['cod_dep' => '76', 'codigo' => '76892', 'nombre' => 'YUMBO'],
            ['cod_dep' => '76', 'codigo' => '76895', 'nombre' => 'ZARZAL'],

            // Vaupés (97)
            ['cod_dep' => '97', 'codigo' => '97001', 'nombre' => 'MITÚ'],
            ['cod_dep' => '97', 'codigo' => '97161', 'nombre' => 'CARURÚ'],
            ['cod_dep' => '97', 'codigo' => '97511', 'nombre' => 'PACOA'],
            ['cod_dep' => '97', 'codigo' => '97666', 'nombre' => 'TARAIRA'],
            ['cod_dep' => '97', 'codigo' => '97777', 'nombre' => 'PAPUNAHUA'],
            ['cod_dep' => '97', 'codigo' => '97889', 'nombre' => 'YAVARATÉ'],

            // Vichada (99)
            ['cod_dep' => '99', 'codigo' => '99001', 'nombre' => 'PUERTO CARREÑO'],
            ['cod_dep' => '99', 'codigo' => '99524', 'nombre' => 'LA PRIMAVERA'],
            ['cod_dep' => '99', 'codigo' => '99624', 'nombre' => 'SANTA ROSALÍA'],
            ['cod_dep' => '99', 'codigo' => '99773', 'nombre' => 'CUMARIBO'],
        ];

        $ciudades = array_merge($ciudades, $batch2, $batch3, $batch4, $batch5, $batch6);

        foreach ($ciudades as $data) {
            $departamento = Departamento::where('codigo', $data['cod_dep'])->first();

            if ($departamento) {
                Ciudad::create([
                    'id_departamento' => $departamento->id_departamento,
                    'codigo' => $data['codigo'],
                    'nombre' => $data['nombre'],
                ]);
            }
        }
    }
}
